<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/member/event.proto

namespace GPBMetadata\Io\Member;

class Event
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xAF\x03\x0A\x15io/member/event.proto\x12\x07members\"\xA3\x02\x0A\x0CEventDetails\x12\x0F\x0A\x07address\x18\x01 \x01(\x09\x12\x0B\x0A\x03lat\x18\x02 \x01(\x01\x12\x0B\x0A\x03lon\x18\x03 \x01(\x01\x12\x0B\x0A\x03alt\x18\x04 \x01(\x05\x12\x17\x0A\x0FexternalEventId\x18\x05 \x01(\x09\x12\x18\x0A\x10externalDeviceId\x18\x06 \x01(\x09\x12\x19\x0A\x11externalServiceId\x18\x07 \x01(\x09\x125\x0A\x08metaData\x18\x08 \x03(\x0B2#.members.EventDetails.MetaDataEntry\x12\x0D\x0A\x05notes\x18\x09 \x01(\x09\x12\x16\x0A\x0EexternalUserId\x18\x0A \x01(\x09\x1A/\x0A\x0DMetaDataEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01B_\x0A\x18com.passkit.grpc.MembersZ,stash.passkit.com/io/model/sdk/go/io/members\xAA\x02\x14PassKit.Grpc.Membersb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

