<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/member/tier.proto

namespace GPBMetadata\Io\Member;

class Tier
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Io\Common\Localization::initOnce();
        \GPBMetadata\Io\Common\CommonObjects::initOnce();
        \GPBMetadata\Io\Common\Expiry::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xEB\x08\x0A\x14io/member/tier.proto\x12\x07members\x1A.protoc-gen-openapiv2/options/annotations.proto\x1A\x1Cio/common/localization.proto\x1A\x1Eio/common/common_objects.proto\x1A\x16io/common/expiry.proto\"\xA3\x06\x0A\x04Tier\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x11\x0A\x09tierIndex\x18\x02 \x01(\x0D\x12\x0C\x0A\x04name\x18\x03 \x01(\x09\x12*\x0A\x0DlocalizedName\x18\x04 \x01(\x0B2\x13.io.LocalizedString\x12\x19\x0A\x11secondaryTierName\x18\x05 \x01(\x09\x127\x0A\x1AlocalizedSecondaryTierName\x18\x06 \x01(\x0B2\x13.io.LocalizedString\x12\x11\x0A\x09programId\x18\x07 \x01(\x09\x12\x16\x0A\x0EpassTemplateId\x18\x08 \x01(\x09\x12\x1A\x0A\x12tierUpgradeMessage\x18\x09 \x01(\x09\x128\x0A\x1BlocalizedTierUpgradeMessage\x18\x0A \x01(\x0B2\x13.io.LocalizedString\x12\x1C\x0A\x14tierDowngradeMessage\x18\x0B \x01(\x09\x12:\x0A\x1DlocalizedTierDowngradeMessage\x18\x0C \x01(\x0B2\x13.io.LocalizedString\x12+\x0A\x07created\x18\x0D \x01(\x0B2\x1A.google.protobuf.Timestamp\x12+\x0A\x07updated\x18\x0E \x01(\x0B2\x1A.google.protobuf.Timestamp\x12\x17\x0A\x0FpointsOverdrawn\x18\x0F \x01(\x08\x12 \x0A\x18secondaryPointsOverdrawn\x18\x10 \x01(\x08\x12*\x0A\x0EexpirySettings\x18\x11 \x01(\x0B2\x12.io.ExpirySettings\x12\x10\x0A\x08timezone\x18\x12 \x01(\x09\x12&\x0A\x12allowTierEnrolment\x18\x13 \x01(\x0B2\x0A.io.PkBool\x12\x11\x0A\x09shortCode\x18\x14 \x01(\x09:\x84\x01\x92A\x80\x01\x0A~*\x04Tier2ATier allows a company to override certain details in the program.\xD2\x01\x02id\xD2\x01\x09tierIndex\xD2\x01\x09programId\xD2\x01\x04name\xD2\x01\x0EpassTemplateId\"5\x0A\x10TierRequestInput\x12\x11\x0A\x09programId\x18\x01 \x01(\x09\x12\x0E\x0A\x06tierId\x18\x02 \x01(\x09B_\x0A\x18com.passkit.grpc.MembersZ,stash.passkit.com/io/model/sdk/go/io/members\xAA\x02\x14PassKit.Grpc.Membersb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

