<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/user/user.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AuditLog represents a log entry for API access.
 *
 * Generated from protobuf message <code>io.AuditLog</code>
 */
class AuditLog extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    protected $timestamp = null;
    /**
     * Generated from protobuf field <code>string companyId = 2;</code>
     */
    protected $companyId = '';
    /**
     * Generated from protobuf field <code>string username = 3;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>.io.UserType userType = 4;</code>
     */
    protected $userType = 0;
    /**
     * Generated from protobuf field <code>.io.Authentication authentication = 5;</code>
     */
    protected $authentication = 0;
    /**
     * Generated from protobuf field <code>.io.Channel channel = 6;</code>
     */
    protected $channel = 0;
    /**
     * Generated from protobuf field <code>string ipAddress = 7;</code>
     */
    protected $ipAddress = '';
    /**
     * Generated from protobuf field <code>string endpoint = 8;</code>
     */
    protected $endpoint = '';
    /**
     * Generated from protobuf field <code>string payload = 9;</code>
     */
    protected $payload = '';
    /**
     * Generated from protobuf field <code>uint32 statusCode = 10;</code>
     */
    protected $statusCode = 0;
    /**
     * Generated from protobuf field <code>string status = 11;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string response = 12;</code>
     */
    protected $response = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $timestamp
     *     @type string $companyId
     *     @type string $username
     *     @type int $userType
     *     @type int $authentication
     *     @type int $channel
     *     @type string $ipAddress
     *     @type string $endpoint
     *     @type string $payload
     *     @type int $statusCode
     *     @type string $status
     *     @type string $response
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\User\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string companyId = 2;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->companyId;
    }

    /**
     * Generated from protobuf field <code>string companyId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->companyId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.UserType userType = 4;</code>
     * @return int
     */
    public function getUserType()
    {
        return $this->userType;
    }

    /**
     * Generated from protobuf field <code>.io.UserType userType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkEnum($var, \Io\UserType::class);
        $this->userType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.Authentication authentication = 5;</code>
     * @return int
     */
    public function getAuthentication()
    {
        return $this->authentication;
    }

    /**
     * Generated from protobuf field <code>.io.Authentication authentication = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAuthentication($var)
    {
        GPBUtil::checkEnum($var, \Io\Authentication::class);
        $this->authentication = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.Channel channel = 6;</code>
     * @return int
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>.io.Channel channel = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkEnum($var, \Io\Channel::class);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ipAddress = 7;</code>
     * @return string
     */
    public function getIpAddress()
    {
        return $this->ipAddress;
    }

    /**
     * Generated from protobuf field <code>string ipAddress = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ipAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 8;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payload = 9;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>string payload = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, True);
        $this->payload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 statusCode = 10;</code>
     * @return int
     */
    public function getStatusCode()
    {
        return $this->statusCode;
    }

    /**
     * Generated from protobuf field <code>uint32 statusCode = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setStatusCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->statusCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 11;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string response = 12;</code>
     * @return string
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>string response = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkString($var, True);
        $this->response = $var;

        return $this;
    }

}

