<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/template.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Colours take a hexcode input.  A '#' prefix is optional.
 *
 * Generated from protobuf message <code>io.Colors</code>
 */
class Colors extends \Google\Protobuf\Internal\Message
{
    /**
     * The background color of the card in hex (e.g. “#ffffff” or "ffffff").
     *
     * Generated from protobuf field <code>string backgroundColor = 1;</code>
     */
    protected $backgroundColor = '';
    /**
     * This customises the color of field label of Apple Wallet pass.
     *
     * Generated from protobuf field <code>string labelColor = 2;</code>
     */
    protected $labelColor = '';
    /**
     * This customises the color of field text or value of Apple Wallet pass.
     *
     * Generated from protobuf field <code>string textColor = 3;</code>
     */
    protected $textColor = '';
    /**
     * Optional undocumented color for text placed over the strip image in Apple Wallet.
     *
     * Generated from protobuf field <code>string stripColor = 4;</code>
     */
    protected $stripColor = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $backgroundColor
     *           The background color of the card in hex (e.g. “#ffffff” or "ffffff").
     *     @type string $labelColor
     *           This customises the color of field label of Apple Wallet pass.
     *     @type string $textColor
     *           This customises the color of field text or value of Apple Wallet pass.
     *     @type string $stripColor
     *           Optional undocumented color for text placed over the strip image in Apple Wallet.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Common\Template::initOnce();
        parent::__construct($data);
    }

    /**
     * The background color of the card in hex (e.g. “#ffffff” or "ffffff").
     *
     * Generated from protobuf field <code>string backgroundColor = 1;</code>
     * @return string
     */
    public function getBackgroundColor()
    {
        return $this->backgroundColor;
    }

    /**
     * The background color of the card in hex (e.g. “#ffffff” or "ffffff").
     *
     * Generated from protobuf field <code>string backgroundColor = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBackgroundColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->backgroundColor = $var;

        return $this;
    }

    /**
     * This customises the color of field label of Apple Wallet pass.
     *
     * Generated from protobuf field <code>string labelColor = 2;</code>
     * @return string
     */
    public function getLabelColor()
    {
        return $this->labelColor;
    }

    /**
     * This customises the color of field label of Apple Wallet pass.
     *
     * Generated from protobuf field <code>string labelColor = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLabelColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->labelColor = $var;

        return $this;
    }

    /**
     * This customises the color of field text or value of Apple Wallet pass.
     *
     * Generated from protobuf field <code>string textColor = 3;</code>
     * @return string
     */
    public function getTextColor()
    {
        return $this->textColor;
    }

    /**
     * This customises the color of field text or value of Apple Wallet pass.
     *
     * Generated from protobuf field <code>string textColor = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTextColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->textColor = $var;

        return $this;
    }

    /**
     * Optional undocumented color for text placed over the strip image in Apple Wallet.
     *
     * Generated from protobuf field <code>string stripColor = 4;</code>
     * @return string
     */
    public function getStripColor()
    {
        return $this->stripColor;
    }

    /**
     * Optional undocumented color for text placed over the strip image in Apple Wallet.
     *
     * Generated from protobuf field <code>string stripColor = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStripColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->stripColor = $var;

        return $this;
    }

}

