<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/job.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.CompletedCsvImport</code>
 */
class CompletedCsvImport extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string fileUrl = 1;</code>
     */
    protected $fileUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fileUrl
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Common\Job::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string fileUrl = 1;</code>
     * @return string
     */
    public function getFileUrl()
    {
        return $this->fileUrl;
    }

    /**
     * Generated from protobuf field <code>string fileUrl = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFileUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->fileUrl = $var;

        return $this;
    }

}

