<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/user/user.proto

namespace Io;

use UnexpectedValueException;

/**
 * DefaultMembershipScanAction enum determines what default actions a user can apply to scanned cards. Users are permitted ot have access to multiple options, but only one can be used at a time.
 *
 * Protobuf type <code>io.DefaultMembershipScanAction</code>
 */
class DefaultMembershipScanAction
{
    /**
     * Zero based enum, don't use 0.
     *
     * Generated from protobuf enum <code>MEMBERSHIP_DEFAULT_NONE = 0;</code>
     */
    const MEMBERSHIP_DEFAULT_NONE = 0;
    /**
     * Set so any card scanned gets a certain amount of points added automatically.
     *
     * Generated from protobuf enum <code>MEMBERSHIP_DEFAULT_EARN_POINTS = 1;</code>
     */
    const MEMBERSHIP_DEFAULT_EARN_POINTS = 1;
    /**
     * Set so any card scanned gets a certain amount of points subtracted automatically.
     *
     * Generated from protobuf enum <code>MEMBERSHIP_DEFAULT_BURN_POINTS = 2;</code>
     */
    const MEMBERSHIP_DEFAULT_BURN_POINTS = 2;
    /**
     * Set so any card scanned gets automatically checked in or out.
     *
     * Generated from protobuf enum <code>MEMBERSHIP_DEFAULT_CHECK_IN_OUT = 4;</code>
     */
    const MEMBERSHIP_DEFAULT_CHECK_IN_OUT = 4;
    /**
     * Set so any card scanned gets automatically validated.
     *
     * Generated from protobuf enum <code>MEMBERSHIP_DEFAULT_VALIDATE = 8;</code>
     */
    const MEMBERSHIP_DEFAULT_VALIDATE = 8;

    private static $valueToName = [
        self::MEMBERSHIP_DEFAULT_NONE => 'MEMBERSHIP_DEFAULT_NONE',
        self::MEMBERSHIP_DEFAULT_EARN_POINTS => 'MEMBERSHIP_DEFAULT_EARN_POINTS',
        self::MEMBERSHIP_DEFAULT_BURN_POINTS => 'MEMBERSHIP_DEFAULT_BURN_POINTS',
        self::MEMBERSHIP_DEFAULT_CHECK_IN_OUT => 'MEMBERSHIP_DEFAULT_CHECK_IN_OUT',
        self::MEMBERSHIP_DEFAULT_VALIDATE => 'MEMBERSHIP_DEFAULT_VALIDATE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

