<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/personal.proto

namespace Io;

use UnexpectedValueException;

/**
 * Gender, as per government issued id.
 *
 * Protobuf type <code>io.Gender</code>
 */
class Gender
{
    /**
     * Use only where gender is not known
     *
     * Generated from protobuf enum <code>NOT_KNOWN = 0;</code>
     */
    const NOT_KNOWN = 0;
    /**
     * Male
     *
     * Generated from protobuf enum <code>MALE = 1;</code>
     */
    const MALE = 1;
    /**
     * Female
     *
     * Generated from protobuf enum <code>FEMALE = 2;</code>
     */
    const FEMALE = 2;

    private static $valueToName = [
        self::NOT_KNOWN => 'NOT_KNOWN',
        self::MALE => 'MALE',
        self::FEMALE => 'FEMALE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

