<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/template.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Pass settings only for Google Pay.
 *
 * Generated from protobuf message <code>io.GooglePaySettings</code>
 */
class GooglePaySettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Pass type
     *
     * Generated from protobuf field <code>.io.GooglePayPassType passType = 1;</code>
     */
    protected $passType = 0;
    /**
     * Android App details
     *
     * Generated from protobuf field <code>.io.GooglePayApp androidApp = 2;</code>
     */
    protected $androidApp = null;
    /**
     * IOS app details
     *
     * Generated from protobuf field <code>.io.GooglePayApp iosApp = 3;</code>
     */
    protected $iosApp = null;
    /**
     * Web app details
     *
     * Generated from protobuf field <code>.io.GooglePayApp webApp = 4;</code>
     */
    protected $webApp = null;
    /**
     * Custom template (takes a JSON ClassTemplateInfo object https://developers.google.com/pay/passes/rest/v1/ClassTemplateInfo)
     *
     * Generated from protobuf field <code>string classTemplateInfo = 5;</code>
     */
    protected $classTemplateInfo = '';
    /**
     * Override template background color
     *
     * Generated from protobuf field <code>string backgroundColor = 6;</code>
     */
    protected $backgroundColor = '';
    /**
     * The pass localisation will be restricted to languages in this list. Currently only available to Boarding Passes and restricted to a single language. Google are working on supporting multiple overrides and we will update this documentation once multiple languages are available.
     *
     * Generated from protobuf field <code>repeated .io.LanguageCode languageOverrides = 7;</code>
     */
    private $languageOverrides;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $passType
     *           Pass type
     *     @type \Io\GooglePayApp $androidApp
     *           Android App details
     *     @type \Io\GooglePayApp $iosApp
     *           IOS app details
     *     @type \Io\GooglePayApp $webApp
     *           Web app details
     *     @type string $classTemplateInfo
     *           Custom template (takes a JSON ClassTemplateInfo object https://developers.google.com/pay/passes/rest/v1/ClassTemplateInfo)
     *     @type string $backgroundColor
     *           Override template background color
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $languageOverrides
     *           The pass localisation will be restricted to languages in this list. Currently only available to Boarding Passes and restricted to a single language. Google are working on supporting multiple overrides and we will update this documentation once multiple languages are available.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Common\Template::initOnce();
        parent::__construct($data);
    }

    /**
     * Pass type
     *
     * Generated from protobuf field <code>.io.GooglePayPassType passType = 1;</code>
     * @return int
     */
    public function getPassType()
    {
        return $this->passType;
    }

    /**
     * Pass type
     *
     * Generated from protobuf field <code>.io.GooglePayPassType passType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPassType($var)
    {
        GPBUtil::checkEnum($var, \Io\GooglePayPassType::class);
        $this->passType = $var;

        return $this;
    }

    /**
     * Android App details
     *
     * Generated from protobuf field <code>.io.GooglePayApp androidApp = 2;</code>
     * @return \Io\GooglePayApp|null
     */
    public function getAndroidApp()
    {
        return isset($this->androidApp) ? $this->androidApp : null;
    }

    public function hasAndroidApp()
    {
        return isset($this->androidApp);
    }

    public function clearAndroidApp()
    {
        unset($this->androidApp);
    }

    /**
     * Android App details
     *
     * Generated from protobuf field <code>.io.GooglePayApp androidApp = 2;</code>
     * @param \Io\GooglePayApp $var
     * @return $this
     */
    public function setAndroidApp($var)
    {
        GPBUtil::checkMessage($var, \Io\GooglePayApp::class);
        $this->androidApp = $var;

        return $this;
    }

    /**
     * IOS app details
     *
     * Generated from protobuf field <code>.io.GooglePayApp iosApp = 3;</code>
     * @return \Io\GooglePayApp|null
     */
    public function getIosApp()
    {
        return isset($this->iosApp) ? $this->iosApp : null;
    }

    public function hasIosApp()
    {
        return isset($this->iosApp);
    }

    public function clearIosApp()
    {
        unset($this->iosApp);
    }

    /**
     * IOS app details
     *
     * Generated from protobuf field <code>.io.GooglePayApp iosApp = 3;</code>
     * @param \Io\GooglePayApp $var
     * @return $this
     */
    public function setIosApp($var)
    {
        GPBUtil::checkMessage($var, \Io\GooglePayApp::class);
        $this->iosApp = $var;

        return $this;
    }

    /**
     * Web app details
     *
     * Generated from protobuf field <code>.io.GooglePayApp webApp = 4;</code>
     * @return \Io\GooglePayApp|null
     */
    public function getWebApp()
    {
        return isset($this->webApp) ? $this->webApp : null;
    }

    public function hasWebApp()
    {
        return isset($this->webApp);
    }

    public function clearWebApp()
    {
        unset($this->webApp);
    }

    /**
     * Web app details
     *
     * Generated from protobuf field <code>.io.GooglePayApp webApp = 4;</code>
     * @param \Io\GooglePayApp $var
     * @return $this
     */
    public function setWebApp($var)
    {
        GPBUtil::checkMessage($var, \Io\GooglePayApp::class);
        $this->webApp = $var;

        return $this;
    }

    /**
     * Custom template (takes a JSON ClassTemplateInfo object https://developers.google.com/pay/passes/rest/v1/ClassTemplateInfo)
     *
     * Generated from protobuf field <code>string classTemplateInfo = 5;</code>
     * @return string
     */
    public function getClassTemplateInfo()
    {
        return $this->classTemplateInfo;
    }

    /**
     * Custom template (takes a JSON ClassTemplateInfo object https://developers.google.com/pay/passes/rest/v1/ClassTemplateInfo)
     *
     * Generated from protobuf field <code>string classTemplateInfo = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setClassTemplateInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->classTemplateInfo = $var;

        return $this;
    }

    /**
     * Override template background color
     *
     * Generated from protobuf field <code>string backgroundColor = 6;</code>
     * @return string
     */
    public function getBackgroundColor()
    {
        return $this->backgroundColor;
    }

    /**
     * Override template background color
     *
     * Generated from protobuf field <code>string backgroundColor = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBackgroundColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->backgroundColor = $var;

        return $this;
    }

    /**
     * The pass localisation will be restricted to languages in this list. Currently only available to Boarding Passes and restricted to a single language. Google are working on supporting multiple overrides and we will update this documentation once multiple languages are available.
     *
     * Generated from protobuf field <code>repeated .io.LanguageCode languageOverrides = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLanguageOverrides()
    {
        return $this->languageOverrides;
    }

    /**
     * The pass localisation will be restricted to languages in this list. Currently only available to Boarding Passes and restricted to a single language. Google are working on supporting multiple overrides and we will update this documentation once multiple languages are available.
     *
     * Generated from protobuf field <code>repeated .io.LanguageCode languageOverrides = 7;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLanguageOverrides($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Io\LanguageCode::class);
        $this->languageOverrides = $arr;

        return $this;
    }

}

