<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/common/integration.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Integration object contains configuration data to integrate PassKit application with third party application.
 *
 * Generated from protobuf message <code>io.IntegrationConfigs</code>
 */
class IntegrationConfigs extends \Google\Protobuf\Internal\Message
{
    /**
     * The uuid for the class object.
     *
     * Generated from protobuf field <code>string classId = 1;</code>
     */
    protected $classId = '';
    /**
     * Key string is enum of ConfigurationType (e.g. WEBHOOK, DB_MYSQL, ZOHO). Value string is a json string of configuration object.
     *
     * Generated from protobuf field <code>map<int32, string> configurations = 2;</code>
     */
    private $configurations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $classId
     *           The uuid for the class object.
     *     @type array|\Google\Protobuf\Internal\MapField $configurations
     *           Key string is enum of ConfigurationType (e.g. WEBHOOK, DB_MYSQL, ZOHO). Value string is a json string of configuration object.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Common\Integration::initOnce();
        parent::__construct($data);
    }

    /**
     * The uuid for the class object.
     *
     * Generated from protobuf field <code>string classId = 1;</code>
     * @return string
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     * The uuid for the class object.
     *
     * Generated from protobuf field <code>string classId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkString($var, True);
        $this->classId = $var;

        return $this;
    }

    /**
     * Key string is enum of ConfigurationType (e.g. WEBHOOK, DB_MYSQL, ZOHO). Value string is a json string of configuration object.
     *
     * Generated from protobuf field <code>map<int32, string> configurations = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getConfigurations()
    {
        return $this->configurations;
    }

    /**
     * Key string is enum of ConfigurationType (e.g. WEBHOOK, DB_MYSQL, ZOHO). Value string is a json string of configuration object.
     *
     * Generated from protobuf field <code>map<int32, string> configurations = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setConfigurations($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::STRING);
        $this->configurations = $arr;

        return $this;
    }

}

