<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/message.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * the protocol that this message is associated with.
     *
     * Generated from protobuf field <code>.io.PassProtocol protocol = 1;</code>
     */
    protected $protocol = 0;
    /**
     * the id of the company that made the message
     *
     * Generated from protobuf field <code>string companyId = 2;</code>
     */
    protected $companyId = '';
    /**
     * the higher level class id for the protocol.
     *
     * Generated from protobuf field <code>string classId = 3;</code>
     */
    protected $classId = '';
    /**
     * the unique id for this message
     *
     * Generated from protobuf field <code>string uuid = 4;</code>
     */
    protected $uuid = '';
    /**
     * the status of the message.
     *
     * Generated from protobuf field <code>.io.MessageStatus status = 5;</code>
     */
    protected $status = 0;
    /**
     * warning of any errors that may have occurred.
     *
     * Generated from protobuf field <code>string warning = 6;</code>
     */
    protected $warning = '';
    /**
     * Optional Image ID; for the Main Image that will be shown in Google Pay (Google Pay only; no image is shown for Apple Wallet).
     *
     * Generated from protobuf field <code>uint32 imageId = 7;</code>
     */
    protected $imageId = 0;
    /**
     * Title (summary) of the message.
     *
     * Generated from protobuf field <code>string title = 8;</code>
     */
    protected $title = '';
    /**
     * Localized title of the message.
     *
     * Generated from protobuf field <code>.io.LocalizedString localizedTitle = 9;</code>
     */
    protected $localizedTitle = null;
    /**
     * Content of the message (finer details).
     *
     * Generated from protobuf field <code>string content = 10;</code>
     */
    protected $content = '';
    /**
     * Localized content of the message.
     *
     * Generated from protobuf field <code>.io.LocalizedString localizedContent = 11;</code>
     */
    protected $localizedContent = null;
    /**
     * Start date indicates when the message is shown on the pass.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp startDate = 12;</code>
     */
    protected $startDate = null;
    /**
     * End date indicates when the message is removed from the pass.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp endDate = 13;</code>
     */
    protected $endDate = null;
    /**
     * optional filter used determine which members qualify for this message.
     *
     * Generated from protobuf field <code>.io.Filter filter = 14;</code>
     */
    protected $filter = null;
    /**
     * number of records this message will be sent to.
     *
     * Generated from protobuf field <code>uint32 recordsMatchingSegment = 15;</code>
     */
    protected $recordsMatchingSegment = 0;
    /**
     * number of records updated with this message.
     *
     * Generated from protobuf field <code>uint32 recordsSuccessfullyUpdate = 16;</code>
     */
    protected $recordsSuccessfullyUpdate = 0;
    /**
     * number of records that failed updated with this message.
     *
     * Generated from protobuf field <code>uint32 recordsFailedToUpdate = 17;</code>
     */
    protected $recordsFailedToUpdate = 0;
    /**
     * The date the message was created in the PassKit system.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 18;</code>
     */
    protected $created = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $protocol
     *           the protocol that this message is associated with.
     *     @type string $companyId
     *           the id of the company that made the message
     *     @type string $classId
     *           the higher level class id for the protocol.
     *     @type string $uuid
     *           the unique id for this message
     *     @type int $status
     *           the status of the message.
     *     @type string $warning
     *           warning of any errors that may have occurred.
     *     @type int $imageId
     *           Optional Image ID; for the Main Image that will be shown in Google Pay (Google Pay only; no image is shown for Apple Wallet).
     *     @type string $title
     *           Title (summary) of the message.
     *     @type \Io\LocalizedString $localizedTitle
     *           Localized title of the message.
     *     @type string $content
     *           Content of the message (finer details).
     *     @type \Io\LocalizedString $localizedContent
     *           Localized content of the message.
     *     @type \Google\Protobuf\Timestamp $startDate
     *           Start date indicates when the message is shown on the pass.
     *     @type \Google\Protobuf\Timestamp $endDate
     *           End date indicates when the message is removed from the pass.
     *     @type \Io\Filter $filter
     *           optional filter used determine which members qualify for this message.
     *     @type int $recordsMatchingSegment
     *           number of records this message will be sent to.
     *     @type int $recordsSuccessfullyUpdate
     *           number of records updated with this message.
     *     @type int $recordsFailedToUpdate
     *           number of records that failed updated with this message.
     *     @type \Google\Protobuf\Timestamp $created
     *           The date the message was created in the PassKit system.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Common\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * the protocol that this message is associated with.
     *
     * Generated from protobuf field <code>.io.PassProtocol protocol = 1;</code>
     * @return int
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * the protocol that this message is associated with.
     *
     * Generated from protobuf field <code>.io.PassProtocol protocol = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProtocol($var)
    {
        GPBUtil::checkEnum($var, \Io\PassProtocol::class);
        $this->protocol = $var;

        return $this;
    }

    /**
     * the id of the company that made the message
     *
     * Generated from protobuf field <code>string companyId = 2;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->companyId;
    }

    /**
     * the id of the company that made the message
     *
     * Generated from protobuf field <code>string companyId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->companyId = $var;

        return $this;
    }

    /**
     * the higher level class id for the protocol.
     *
     * Generated from protobuf field <code>string classId = 3;</code>
     * @return string
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     * the higher level class id for the protocol.
     *
     * Generated from protobuf field <code>string classId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkString($var, True);
        $this->classId = $var;

        return $this;
    }

    /**
     * the unique id for this message
     *
     * Generated from protobuf field <code>string uuid = 4;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * the unique id for this message
     *
     * Generated from protobuf field <code>string uuid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * the status of the message.
     *
     * Generated from protobuf field <code>.io.MessageStatus status = 5;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * the status of the message.
     *
     * Generated from protobuf field <code>.io.MessageStatus status = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Io\MessageStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * warning of any errors that may have occurred.
     *
     * Generated from protobuf field <code>string warning = 6;</code>
     * @return string
     */
    public function getWarning()
    {
        return $this->warning;
    }

    /**
     * warning of any errors that may have occurred.
     *
     * Generated from protobuf field <code>string warning = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWarning($var)
    {
        GPBUtil::checkString($var, True);
        $this->warning = $var;

        return $this;
    }

    /**
     * Optional Image ID; for the Main Image that will be shown in Google Pay (Google Pay only; no image is shown for Apple Wallet).
     *
     * Generated from protobuf field <code>uint32 imageId = 7;</code>
     * @return int
     */
    public function getImageId()
    {
        return $this->imageId;
    }

    /**
     * Optional Image ID; for the Main Image that will be shown in Google Pay (Google Pay only; no image is shown for Apple Wallet).
     *
     * Generated from protobuf field <code>uint32 imageId = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setImageId($var)
    {
        GPBUtil::checkUint32($var);
        $this->imageId = $var;

        return $this;
    }

    /**
     * Title (summary) of the message.
     *
     * Generated from protobuf field <code>string title = 8;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Title (summary) of the message.
     *
     * Generated from protobuf field <code>string title = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Localized title of the message.
     *
     * Generated from protobuf field <code>.io.LocalizedString localizedTitle = 9;</code>
     * @return \Io\LocalizedString|null
     */
    public function getLocalizedTitle()
    {
        return isset($this->localizedTitle) ? $this->localizedTitle : null;
    }

    public function hasLocalizedTitle()
    {
        return isset($this->localizedTitle);
    }

    public function clearLocalizedTitle()
    {
        unset($this->localizedTitle);
    }

    /**
     * Localized title of the message.
     *
     * Generated from protobuf field <code>.io.LocalizedString localizedTitle = 9;</code>
     * @param \Io\LocalizedString $var
     * @return $this
     */
    public function setLocalizedTitle($var)
    {
        GPBUtil::checkMessage($var, \Io\LocalizedString::class);
        $this->localizedTitle = $var;

        return $this;
    }

    /**
     * Content of the message (finer details).
     *
     * Generated from protobuf field <code>string content = 10;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Content of the message (finer details).
     *
     * Generated from protobuf field <code>string content = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Localized content of the message.
     *
     * Generated from protobuf field <code>.io.LocalizedString localizedContent = 11;</code>
     * @return \Io\LocalizedString|null
     */
    public function getLocalizedContent()
    {
        return isset($this->localizedContent) ? $this->localizedContent : null;
    }

    public function hasLocalizedContent()
    {
        return isset($this->localizedContent);
    }

    public function clearLocalizedContent()
    {
        unset($this->localizedContent);
    }

    /**
     * Localized content of the message.
     *
     * Generated from protobuf field <code>.io.LocalizedString localizedContent = 11;</code>
     * @param \Io\LocalizedString $var
     * @return $this
     */
    public function setLocalizedContent($var)
    {
        GPBUtil::checkMessage($var, \Io\LocalizedString::class);
        $this->localizedContent = $var;

        return $this;
    }

    /**
     * Start date indicates when the message is shown on the pass.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp startDate = 12;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartDate()
    {
        return isset($this->startDate) ? $this->startDate : null;
    }

    public function hasStartDate()
    {
        return isset($this->startDate);
    }

    public function clearStartDate()
    {
        unset($this->startDate);
    }

    /**
     * Start date indicates when the message is shown on the pass.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp startDate = 12;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->startDate = $var;

        return $this;
    }

    /**
     * End date indicates when the message is removed from the pass.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp endDate = 13;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEndDate()
    {
        return isset($this->endDate) ? $this->endDate : null;
    }

    public function hasEndDate()
    {
        return isset($this->endDate);
    }

    public function clearEndDate()
    {
        unset($this->endDate);
    }

    /**
     * End date indicates when the message is removed from the pass.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp endDate = 13;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->endDate = $var;

        return $this;
    }

    /**
     * optional filter used determine which members qualify for this message.
     *
     * Generated from protobuf field <code>.io.Filter filter = 14;</code>
     * @return \Io\Filter|null
     */
    public function getFilter()
    {
        return isset($this->filter) ? $this->filter : null;
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * optional filter used determine which members qualify for this message.
     *
     * Generated from protobuf field <code>.io.Filter filter = 14;</code>
     * @param \Io\Filter $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Io\Filter::class);
        $this->filter = $var;

        return $this;
    }

    /**
     * number of records this message will be sent to.
     *
     * Generated from protobuf field <code>uint32 recordsMatchingSegment = 15;</code>
     * @return int
     */
    public function getRecordsMatchingSegment()
    {
        return $this->recordsMatchingSegment;
    }

    /**
     * number of records this message will be sent to.
     *
     * Generated from protobuf field <code>uint32 recordsMatchingSegment = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setRecordsMatchingSegment($var)
    {
        GPBUtil::checkUint32($var);
        $this->recordsMatchingSegment = $var;

        return $this;
    }

    /**
     * number of records updated with this message.
     *
     * Generated from protobuf field <code>uint32 recordsSuccessfullyUpdate = 16;</code>
     * @return int
     */
    public function getRecordsSuccessfullyUpdate()
    {
        return $this->recordsSuccessfullyUpdate;
    }

    /**
     * number of records updated with this message.
     *
     * Generated from protobuf field <code>uint32 recordsSuccessfullyUpdate = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setRecordsSuccessfullyUpdate($var)
    {
        GPBUtil::checkUint32($var);
        $this->recordsSuccessfullyUpdate = $var;

        return $this;
    }

    /**
     * number of records that failed updated with this message.
     *
     * Generated from protobuf field <code>uint32 recordsFailedToUpdate = 17;</code>
     * @return int
     */
    public function getRecordsFailedToUpdate()
    {
        return $this->recordsFailedToUpdate;
    }

    /**
     * number of records that failed updated with this message.
     *
     * Generated from protobuf field <code>uint32 recordsFailedToUpdate = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setRecordsFailedToUpdate($var)
    {
        GPBUtil::checkUint32($var);
        $this->recordsFailedToUpdate = $var;

        return $this;
    }

    /**
     * The date the message was created in the PassKit system.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 18;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreated()
    {
        return isset($this->created) ? $this->created : null;
    }

    public function hasCreated()
    {
        return isset($this->created);
    }

    public function clearCreated()
    {
        unset($this->created);
    }

    /**
     * The date the message was created in the PassKit system.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 18;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created = $var;

        return $this;
    }

}

