<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/common/template.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.NFC</code>
 */
class NFC extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool enabled = 1;</code>
     */
    protected $enabled = false;
    /**
     * Leave empty to use your default account keys, or provide the key ID of the public / private keypair you have provided.
     *
     * Generated from protobuf field <code>string certificateId = 2;</code>
     */
    protected $certificateId = '';
    /**
     * A maximum of 64 characters can be provided
     *
     * Generated from protobuf field <code>string payload = 3;</code>
     */
    protected $payload = '';
    /**
     * iCloud binding restricts the use of the pass to a single iCloud account. Passes cannot be shared and care should be given when distributing passes to ensure that the pass goes to the correct user.  Users will need to have the iOS 17 or above, and no barcodes will be permitted on the pass.
     *
     * Generated from protobuf field <code>bool iCloudBound = 4;</code>
     */
    protected $iCloudBound = false;
    /**
     * If not provided, a default learn more URL and your organization name will be used.
     *
     * Generated from protobuf field <code>.io.BindingInfo bindingInfo = 5;</code>
     */
    protected $bindingInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enabled
     *     @type string $certificateId
     *           Leave empty to use your default account keys, or provide the key ID of the public / private keypair you have provided.
     *     @type string $payload
     *           A maximum of 64 characters can be provided
     *     @type bool $iCloudBound
     *           iCloud binding restricts the use of the pass to a single iCloud account. Passes cannot be shared and care should be given when distributing passes to ensure that the pass goes to the correct user.  Users will need to have the iOS 17 or above, and no barcodes will be permitted on the pass.
     *     @type \Io\BindingInfo $bindingInfo
     *           If not provided, a default learn more URL and your organization name will be used.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Common\Template::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Generated from protobuf field <code>bool enabled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Leave empty to use your default account keys, or provide the key ID of the public / private keypair you have provided.
     *
     * Generated from protobuf field <code>string certificateId = 2;</code>
     * @return string
     */
    public function getCertificateId()
    {
        return $this->certificateId;
    }

    /**
     * Leave empty to use your default account keys, or provide the key ID of the public / private keypair you have provided.
     *
     * Generated from protobuf field <code>string certificateId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCertificateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->certificateId = $var;

        return $this;
    }

    /**
     * A maximum of 64 characters can be provided
     *
     * Generated from protobuf field <code>string payload = 3;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * A maximum of 64 characters can be provided
     *
     * Generated from protobuf field <code>string payload = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, True);
        $this->payload = $var;

        return $this;
    }

    /**
     * iCloud binding restricts the use of the pass to a single iCloud account. Passes cannot be shared and care should be given when distributing passes to ensure that the pass goes to the correct user.  Users will need to have the iOS 17 or above, and no barcodes will be permitted on the pass.
     *
     * Generated from protobuf field <code>bool iCloudBound = 4;</code>
     * @return bool
     */
    public function getICloudBound()
    {
        return $this->iCloudBound;
    }

    /**
     * iCloud binding restricts the use of the pass to a single iCloud account. Passes cannot be shared and care should be given when distributing passes to ensure that the pass goes to the correct user.  Users will need to have the iOS 17 or above, and no barcodes will be permitted on the pass.
     *
     * Generated from protobuf field <code>bool iCloudBound = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setICloudBound($var)
    {
        GPBUtil::checkBool($var);
        $this->iCloudBound = $var;

        return $this;
    }

    /**
     * If not provided, a default learn more URL and your organization name will be used.
     *
     * Generated from protobuf field <code>.io.BindingInfo bindingInfo = 5;</code>
     * @return \Io\BindingInfo|null
     */
    public function getBindingInfo()
    {
        return $this->bindingInfo;
    }

    public function hasBindingInfo()
    {
        return isset($this->bindingInfo);
    }

    public function clearBindingInfo()
    {
        unset($this->bindingInfo);
    }

    /**
     * If not provided, a default learn more URL and your organization name will be used.
     *
     * Generated from protobuf field <code>.io.BindingInfo bindingInfo = 5;</code>
     * @param \Io\BindingInfo $var
     * @return $this
     */
    public function setBindingInfo($var)
    {
        GPBUtil::checkMessage($var, \Io\BindingInfo::class);
        $this->bindingInfo = $var;

        return $this;
    }

}

