<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/common/template.proto

namespace Io;

use UnexpectedValueException;

/**
 * Protobuf type <code>io.NumberStyle</code>
 */
class NumberStyle
{
    /**
     * Generated from protobuf enum <code>NUMBER_STYLE_DO_NOT_USE = 0;</code>
     */
    const NUMBER_STYLE_DO_NOT_USE = 0;
    /**
     * Generated from protobuf enum <code>NUMBER_STYLE_DECIMAL = 1;</code>
     */
    const NUMBER_STYLE_DECIMAL = 1;
    /**
     * Generated from protobuf enum <code>NUMBER_STYLE_PERCENT = 2;</code>
     */
    const NUMBER_STYLE_PERCENT = 2;
    /**
     * Generated from protobuf enum <code>NUMBER_STYLE_SCIENTIFIC = 3;</code>
     */
    const NUMBER_STYLE_SCIENTIFIC = 3;
    /**
     * Generated from protobuf enum <code>NUMBER_STYLE_SPELL = 4;</code>
     */
    const NUMBER_STYLE_SPELL = 4;

    private static $valueToName = [
        self::NUMBER_STYLE_DO_NOT_USE => 'NUMBER_STYLE_DO_NOT_USE',
        self::NUMBER_STYLE_DECIMAL => 'NUMBER_STYLE_DECIMAL',
        self::NUMBER_STYLE_PERCENT => 'NUMBER_STYLE_PERCENT',
        self::NUMBER_STYLE_SCIENTIFIC => 'NUMBER_STYLE_SCIENTIFIC',
        self::NUMBER_STYLE_SPELL => 'NUMBER_STYLE_SPELL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

