<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/common/template.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Sets a position of field on the pass. Priority attribute allows you to change the order of field within the section.
 *
 * Generated from protobuf message <code>io.PositionSettings</code>
 */
class PositionSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Selects a section to render a field.
     *
     * Generated from protobuf field <code>.io.FieldSection section = 1;</code>
     */
    protected $section = 0;
    /**
     * The field section has certain number of fields they can contain. The priority indicates the position of the section.
     *
     * Generated from protobuf field <code>uint32 priority = 2;</code>
     */
    protected $priority = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $section
     *           Selects a section to render a field.
     *     @type int $priority
     *           The field section has certain number of fields they can contain. The priority indicates the position of the section.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Common\Template::initOnce();
        parent::__construct($data);
    }

    /**
     * Selects a section to render a field.
     *
     * Generated from protobuf field <code>.io.FieldSection section = 1;</code>
     * @return int
     */
    public function getSection()
    {
        return $this->section;
    }

    /**
     * Selects a section to render a field.
     *
     * Generated from protobuf field <code>.io.FieldSection section = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSection($var)
    {
        GPBUtil::checkEnum($var, \Io\FieldSection::class);
        $this->section = $var;

        return $this;
    }

    /**
     * The field section has certain number of fields they can contain. The priority indicates the position of the section.
     *
     * Generated from protobuf field <code>uint32 priority = 2;</code>
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * The field section has certain number of fields they can contain. The priority indicates the position of the section.
     *
     * Generated from protobuf field <code>uint32 priority = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkUint32($var);
        $this->priority = $var;

        return $this;
    }

}

