<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/common_objects.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.Protocol</code>
 */
class Protocol extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.Protocol protocol = 1;</code>
     */
    protected $protocol = null;
    /**
     * Generated from protobuf field <code>string classId = 2;</code>
     */
    protected $classId = '';
    /**
     * Optional pagination criteria. If not provided, then all passes for the class will be selected.
     *
     * Generated from protobuf field <code>.io.Pagination pagination = 3;</code>
     */
    protected $pagination = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Protocol $protocol
     *     @type string $classId
     *     @type \Io\Pagination $pagination
     *           Optional pagination criteria. If not provided, then all passes for the class will be selected.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Common\CommonObjects::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.Protocol protocol = 1;</code>
     * @return \Io\Protocol|null
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    public function hasProtocol()
    {
        return isset($this->protocol);
    }

    public function clearProtocol()
    {
        unset($this->protocol);
    }

    /**
     * Generated from protobuf field <code>.io.Protocol protocol = 1;</code>
     * @param \Io\Protocol $var
     * @return $this
     */
    public function setProtocol($var)
    {
        GPBUtil::checkMessage($var, \Io\Protocol::class);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string classId = 2;</code>
     * @return string
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     * Generated from protobuf field <code>string classId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkString($var, True);
        $this->classId = $var;

        return $this;
    }

    /**
     * Optional pagination criteria. If not provided, then all passes for the class will be selected.
     *
     * Generated from protobuf field <code>.io.Pagination pagination = 3;</code>
     * @return \Io\Pagination|null
     */
    public function getPagination()
    {
        return $this->pagination;
    }

    public function hasPagination()
    {
        return isset($this->pagination);
    }

    public function clearPagination()
    {
        unset($this->pagination);
    }

    /**
     * Optional pagination criteria. If not provided, then all passes for the class will be selected.
     *
     * Generated from protobuf field <code>.io.Pagination pagination = 3;</code>
     * @param \Io\Pagination $var
     * @return $this
     */
    public function setPagination($var)
    {
        GPBUtil::checkMessage($var, \Io\Pagination::class);
        $this->pagination = $var;

        return $this;
    }

}

