<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/user/user.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.ResourcePermissions</code>
 */
class ResourcePermissions extends \Google\Protobuf\Internal\Message
{
    protected $ProjectPermissions;
    protected $CertificatePermissions;
    protected $MembershipProgramPermissions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\ProjectsList $allowedProjects
     *     @type \Io\ProjectsList $disallowedProjects
     *     @type \Io\CertificatesList $allowedCertificates
     *     @type \Io\CertificatesList $disallowedCertificates
     *     @type \Io\ProtocolList $allowedPrograms
     *     @type \Io\ProtocolList $disallowedPrograms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\User\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.ProjectsList allowedProjects = 1;</code>
     * @return \Io\ProjectsList|null
     */
    public function getAllowedProjects()
    {
        return $this->readOneof(1);
    }

    public function hasAllowedProjects()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.io.ProjectsList allowedProjects = 1;</code>
     * @param \Io\ProjectsList $var
     * @return $this
     */
    public function setAllowedProjects($var)
    {
        GPBUtil::checkMessage($var, \Io\ProjectsList::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.ProjectsList disallowedProjects = 2;</code>
     * @return \Io\ProjectsList|null
     */
    public function getDisallowedProjects()
    {
        return $this->readOneof(2);
    }

    public function hasDisallowedProjects()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.io.ProjectsList disallowedProjects = 2;</code>
     * @param \Io\ProjectsList $var
     * @return $this
     */
    public function setDisallowedProjects($var)
    {
        GPBUtil::checkMessage($var, \Io\ProjectsList::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.CertificatesList allowedCertificates = 3;</code>
     * @return \Io\CertificatesList|null
     */
    public function getAllowedCertificates()
    {
        return $this->readOneof(3);
    }

    public function hasAllowedCertificates()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.io.CertificatesList allowedCertificates = 3;</code>
     * @param \Io\CertificatesList $var
     * @return $this
     */
    public function setAllowedCertificates($var)
    {
        GPBUtil::checkMessage($var, \Io\CertificatesList::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.CertificatesList disallowedCertificates = 4;</code>
     * @return \Io\CertificatesList|null
     */
    public function getDisallowedCertificates()
    {
        return $this->readOneof(4);
    }

    public function hasDisallowedCertificates()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.io.CertificatesList disallowedCertificates = 4;</code>
     * @param \Io\CertificatesList $var
     * @return $this
     */
    public function setDisallowedCertificates($var)
    {
        GPBUtil::checkMessage($var, \Io\CertificatesList::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.ProtocolList allowedPrograms = 5;</code>
     * @return \Io\ProtocolList|null
     */
    public function getAllowedPrograms()
    {
        return $this->readOneof(5);
    }

    public function hasAllowedPrograms()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.io.ProtocolList allowedPrograms = 5;</code>
     * @param \Io\ProtocolList $var
     * @return $this
     */
    public function setAllowedPrograms($var)
    {
        GPBUtil::checkMessage($var, \Io\ProtocolList::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.ProtocolList disallowedPrograms = 6;</code>
     * @return \Io\ProtocolList|null
     */
    public function getDisallowedPrograms()
    {
        return $this->readOneof(6);
    }

    public function hasDisallowedPrograms()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.io.ProtocolList disallowedPrograms = 6;</code>
     * @param \Io\ProtocolList $var
     * @return $this
     */
    public function setDisallowedPrograms($var)
    {
        GPBUtil::checkMessage($var, \Io\ProtocolList::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getProjectPermissions()
    {
        return $this->whichOneof("ProjectPermissions");
    }

    /**
     * @return string
     */
    public function getCertificatePermissions()
    {
        return $this->whichOneof("CertificatePermissions");
    }

    /**
     * @return string
     */
    public function getMembershipProgramPermissions()
    {
        return $this->whichOneof("MembershipProgramPermissions");
    }

}

