<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/image/image.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.StampImagePreview</code>
 */
class StampImagePreview extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string preview = 1;</code>
     */
    protected $preview = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $preview
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Image\Image::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string preview = 1;</code>
     * @return string
     */
    public function getPreview()
    {
        return $this->preview;
    }

    /**
     * Generated from protobuf field <code>string preview = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPreview($var)
    {
        GPBUtil::checkString($var, True);
        $this->preview = $var;

        return $this;
    }

}

