<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/certificate/certificate.proto

namespace Io;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.TLSCertificateRequest</code>
 */
class TLSCertificateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes certificate = 1;</code>
     */
    protected $certificate = '';
    /**
     * Generated from protobuf field <code>bytes caChain = 2;</code>
     */
    protected $caChain = '';
    /**
     * Generated from protobuf field <code>bytes privateKey = 3;</code>
     */
    protected $privateKey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $certificate
     *     @type string $caChain
     *     @type string $privateKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Certificate\Certificate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes certificate = 1;</code>
     * @return string
     */
    public function getCertificate()
    {
        return $this->certificate;
    }

    /**
     * Generated from protobuf field <code>bytes certificate = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkString($var, False);
        $this->certificate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes caChain = 2;</code>
     * @return string
     */
    public function getCaChain()
    {
        return $this->caChain;
    }

    /**
     * Generated from protobuf field <code>bytes caChain = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCaChain($var)
    {
        GPBUtil::checkString($var, False);
        $this->caChain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes privateKey = 3;</code>
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->privateKey;
    }

    /**
     * Generated from protobuf field <code>bytes privateKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->privateKey = $var;

        return $this;
    }

}

