<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/common_objects.proto

namespace Io;

use UnexpectedValueException;

/**
 * Protobuf type <code>io.Toggle</code>
 */
class Toggle
{
    /**
     * Generated from protobuf enum <code>DO_NOT_USE = 0;</code>
     */
    const DO_NOT_USE = 0;
    /**
     * Generated from protobuf enum <code>ON = 1;</code>
     */
    const ON = 1;
    /**
     * Generated from protobuf enum <code>OFF = 2;</code>
     */
    const OFF = 2;

    private static $valueToName = [
        self::DO_NOT_USE => 'DO_NOT_USE',
        self::ON => 'ON',
        self::OFF => 'OFF',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

