<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/common/common_objects.proto

namespace Io;

use UnexpectedValueException;

/**
 * UsageType is used to indicate where a field or link is used / rendered
 *
 * Protobuf type <code>io.UsageType</code>
 */
class UsageType
{
    /**
     * Generated from protobuf enum <code>NO_USAGE = 0;</code>
     */
    const NO_USAGE = 0;
    /**
     * Rendered on Apple Wallet
     *
     * Generated from protobuf enum <code>USAGE_APPLE_WALLET = 1;</code>
     */
    const USAGE_APPLE_WALLET = 1;
    /**
     * Rendered on Google Pay
     *
     * Generated from protobuf enum <code>USAGE_GOOGLE_PAY = 2;</code>
     */
    const USAGE_GOOGLE_PAY = 2;
    /**
     * Rendered on data collection page
     *
     * Generated from protobuf enum <code>USAGE_DATA_COLLECTION_PAGE = 4;</code>
     */
    const USAGE_DATA_COLLECTION_PAGE = 4;

    private static $valueToName = [
        self::NO_USAGE => 'NO_USAGE',
        self::USAGE_APPLE_WALLET => 'USAGE_APPLE_WALLET',
        self::USAGE_GOOGLE_PAY => 'USAGE_GOOGLE_PAY',
        self::USAGE_DATA_COLLECTION_PAGE => 'USAGE_DATA_COLLECTION_PAGE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

