<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/event_tickets/ticket_type.proto

namespace GPBMetadata\Io\EventTickets;

class TicketType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Io\Common\Localization::initOnce();
        \GPBMetadata\Io\Common\Filter::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAD\x09\x0A\"io/event_tickets/ticket_type.proto\x12\x0Devent_tickets\x1A\x1Cio/common/localization.proto\x1A\x16io/common/filter.proto\x1A.protoc-gen-openapiv2/options/annotations.proto\"\xBF\x04\x0A\x0ATicketType\x12\x11\x0A\x02id\x18\x01 \x01(\x09B\x05\x92A\x02@\x01\x12\x0B\x0A\x03uid\x18\x02 \x01(\x09\x12\x14\x0A\x0CproductionId\x18\x03 \x01(\x09\x12\x0C\x0A\x04name\x18\x04 \x01(\x09\x12*\x0A\x0DlocalizedName\x18\x05 \x01(\x0B2\x13.io.LocalizedString\x12\x1C\x0A\x14ticketTypeConditions\x18\x06 \x01(\x09\x12:\x0A\x1DlocalizedTicketTypeConditions\x18\x07 \x01(\x0B2\x13.io.LocalizedString\x12\"\x0A\x1AbeforeRedeemPassTemplateId\x18\x08 \x01(\x09\x12!\x0A\x19afterRedeemPassTemplateId\x18\x09 \x01(\x09\x122\x0A\x07created\x18\x0A \x01(\x0B2\x1A.google.protobuf.TimestampB\x05\x92A\x02@\x01\x122\x0A\x07updated\x18\x0B \x01(\x0B2\x1A.google.protobuf.TimestampB\x05\x92A\x02@\x01:\xB7\x01\x92A\xB3\x01\x0A\xB0\x01*\x0BTicket Type2nTicket Type holds details about the ticket type, and links to the before & after redeem Pass Template Designs.\xD2\x01\x0CproductionId\xD2\x01\x04name\xD2\x01\x1AbeforeRedeemPassTemplateId\"4\x0A\x0FGetByUidRequest\x12\x14\x0A\x0CproductionId\x18\x01 \x01(\x09\x12\x0B\x0A\x03uid\x18\x02 \x01(\x09\"\xD3\x01\x0A\x17TicketTypeLimitedFields\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0B\x0A\x03uid\x18\x02 \x01(\x09\x12\x0C\x0A\x04name\x18\x03 \x01(\x09:\x90\x01\x92A\x8C\x01\x0A\x89\x01*\x17Ticket Type (Light ver)2nTicket Type holds details about the ticket type, and links to the before & after redeem Pass Template Designs.\"K\x0A\x15TicketTypeListRequest\x12\x14\x0A\x0CproductionId\x18\x01 \x01(\x09\x12\x1C\x0A\x07filters\x18\x02 \x01(\x0B2\x0B.io.FiltersBo\x0A\x1Dcom.passkit.grpc.EventTicketsZ2stash.passkit.com/io/model/sdk/go/io/event_tickets\xAA\x02\x19PassKit.Grpc.EventTicketsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

