<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protoc-gen-openapiv2/options/openapiv2.proto

namespace Grpc\Gateway\Protoc_gen_openapiv2\Options;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * `Operation` is a representation of OpenAPI v2 specification's Operation object.
 * See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#operationObject
 * Example:
 *  service EchoService {
 *    rpc Echo(SimpleMessage) returns (SimpleMessage) {
 *      option (google.api.http) = {
 *        get: "/v1/example/echo/{id}"
 *      };
 *      option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
 *        summary: "Get a message.";
 *        operation_id: "getMessage";
 *        tags: "echo";
 *        responses: {
 *          key: "200"
 *            value: {
 *            description: "OK";
 *          }
 *        }
 *      };
 *    }
 *  }
 *
 * Generated from protobuf message <code>grpc.gateway.protoc_gen_openapiv2.options.Operation</code>
 */
class Operation extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     *
     * Generated from protobuf field <code>repeated string tags = 1;</code>
     */
    private $tags;
    /**
     * A short summary of what the operation does. For maximum readability in the
     * swagger-ui, this field SHOULD be less than 120 characters.
     *
     * Generated from protobuf field <code>string summary = 2;</code>
     */
    protected $summary = '';
    /**
     * A verbose explanation of the operation behavior. GFM syntax can be used for
     * rich text representation.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Additional external documentation for this operation.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 4;</code>
     */
    protected $external_docs = null;
    /**
     * Unique string used to identify the operation. The id MUST be unique among
     * all operations described in the API. Tools and libraries MAY use the
     * operationId to uniquely identify an operation, therefore, it is recommended
     * to follow common programming naming conventions.
     *
     * Generated from protobuf field <code>string operation_id = 5;</code>
     */
    protected $operation_id = '';
    /**
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     *
     * Generated from protobuf field <code>repeated string consumes = 6;</code>
     */
    private $consumes;
    /**
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     *
     * Generated from protobuf field <code>repeated string produces = 7;</code>
     */
    private $produces;
    /**
     * The list of possible responses as they are returned from executing this
     * operation.
     *
     * Generated from protobuf field <code>map<string, .grpc.gateway.protoc_gen_openapiv2.options.Response> responses = 9;</code>
     */
    private $responses;
    /**
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     *
     * Generated from protobuf field <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     */
    private $schemes;
    /**
     * Declares this operation to be deprecated. Usage of the declared operation
     * should be refrained. Default value is false.
     *
     * Generated from protobuf field <code>bool deprecated = 11;</code>
     */
    protected $deprecated = false;
    /**
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     *
     * Generated from protobuf field <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     */
    private $security;
    /**
     * Custom properties that start with "x-" such as "x-foo" used to describe
     * extra functionality that is not covered by the standard OpenAPI Specification.
     * See: https://swagger.io/docs/specification/2-0/swagger-extensions/
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> extensions = 13;</code>
     */
    private $extensions;
    /**
     * Custom parameters such as HTTP request headers.
     * See: https://swagger.io/docs/specification/2-0/describing-parameters/
     * and https://swagger.io/specification/v2/#parameter-object.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.Parameters parameters = 14;</code>
     */
    protected $parameters = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $tags
     *           A list of tags for API documentation control. Tags can be used for logical
     *           grouping of operations by resources or any other qualifier.
     *     @type string $summary
     *           A short summary of what the operation does. For maximum readability in the
     *           swagger-ui, this field SHOULD be less than 120 characters.
     *     @type string $description
     *           A verbose explanation of the operation behavior. GFM syntax can be used for
     *           rich text representation.
     *     @type \Grpc\Gateway\Protoc_gen_openapiv2\Options\ExternalDocumentation $external_docs
     *           Additional external documentation for this operation.
     *     @type string $operation_id
     *           Unique string used to identify the operation. The id MUST be unique among
     *           all operations described in the API. Tools and libraries MAY use the
     *           operationId to uniquely identify an operation, therefore, it is recommended
     *           to follow common programming naming conventions.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $consumes
     *           A list of MIME types the operation can consume. This overrides the consumes
     *           definition at the OpenAPI Object. An empty value MAY be used to clear the
     *           global definition. Value MUST be as described under Mime Types.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $produces
     *           A list of MIME types the operation can produce. This overrides the produces
     *           definition at the OpenAPI Object. An empty value MAY be used to clear the
     *           global definition. Value MUST be as described under Mime Types.
     *     @type array|\Google\Protobuf\Internal\MapField $responses
     *           The list of possible responses as they are returned from executing this
     *           operation.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $schemes
     *           The transfer protocol for the operation. Values MUST be from the list:
     *           "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     *           schemes definition.
     *     @type bool $deprecated
     *           Declares this operation to be deprecated. Usage of the declared operation
     *           should be refrained. Default value is false.
     *     @type array<\Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityRequirement>|\Google\Protobuf\Internal\RepeatedField $security
     *           A declaration of which security schemes are applied for this operation. The
     *           list of values describes alternative security schemes that can be used
     *           (that is, there is a logical OR between the security requirements). This
     *           definition overrides any declared top-level security. To remove a top-level
     *           security declaration, an empty array can be used.
     *     @type array|\Google\Protobuf\Internal\MapField $extensions
     *           Custom properties that start with "x-" such as "x-foo" used to describe
     *           extra functionality that is not covered by the standard OpenAPI Specification.
     *           See: https://swagger.io/docs/specification/2-0/swagger-extensions/
     *     @type \Grpc\Gateway\Protoc_gen_openapiv2\Options\Parameters $parameters
     *           Custom parameters such as HTTP request headers.
     *           See: https://swagger.io/docs/specification/2-0/describing-parameters/
     *           and https://swagger.io/specification/v2/#parameter-object.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProtocGenOpenapiv2\Options\Openapiv2::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     *
     * Generated from protobuf field <code>repeated string tags = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     *
     * Generated from protobuf field <code>repeated string tags = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * A short summary of what the operation does. For maximum readability in the
     * swagger-ui, this field SHOULD be less than 120 characters.
     *
     * Generated from protobuf field <code>string summary = 2;</code>
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * A short summary of what the operation does. For maximum readability in the
     * swagger-ui, this field SHOULD be less than 120 characters.
     *
     * Generated from protobuf field <code>string summary = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkString($var, True);
        $this->summary = $var;

        return $this;
    }

    /**
     * A verbose explanation of the operation behavior. GFM syntax can be used for
     * rich text representation.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * A verbose explanation of the operation behavior. GFM syntax can be used for
     * rich text representation.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Additional external documentation for this operation.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 4;</code>
     * @return \Grpc\Gateway\Protoc_gen_openapiv2\Options\ExternalDocumentation|null
     */
    public function getExternalDocs()
    {
        return $this->external_docs;
    }

    public function hasExternalDocs()
    {
        return isset($this->external_docs);
    }

    public function clearExternalDocs()
    {
        unset($this->external_docs);
    }

    /**
     * Additional external documentation for this operation.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 4;</code>
     * @param \Grpc\Gateway\Protoc_gen_openapiv2\Options\ExternalDocumentation $var
     * @return $this
     */
    public function setExternalDocs($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Gateway\Protoc_gen_openapiv2\Options\ExternalDocumentation::class);
        $this->external_docs = $var;

        return $this;
    }

    /**
     * Unique string used to identify the operation. The id MUST be unique among
     * all operations described in the API. Tools and libraries MAY use the
     * operationId to uniquely identify an operation, therefore, it is recommended
     * to follow common programming naming conventions.
     *
     * Generated from protobuf field <code>string operation_id = 5;</code>
     * @return string
     */
    public function getOperationId()
    {
        return $this->operation_id;
    }

    /**
     * Unique string used to identify the operation. The id MUST be unique among
     * all operations described in the API. Tools and libraries MAY use the
     * operationId to uniquely identify an operation, therefore, it is recommended
     * to follow common programming naming conventions.
     *
     * Generated from protobuf field <code>string operation_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->operation_id = $var;

        return $this;
    }

    /**
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     *
     * Generated from protobuf field <code>repeated string consumes = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConsumes()
    {
        return $this->consumes;
    }

    /**
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     *
     * Generated from protobuf field <code>repeated string consumes = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConsumes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->consumes = $arr;

        return $this;
    }

    /**
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     *
     * Generated from protobuf field <code>repeated string produces = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProduces()
    {
        return $this->produces;
    }

    /**
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     *
     * Generated from protobuf field <code>repeated string produces = 7;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProduces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->produces = $arr;

        return $this;
    }

    /**
     * The list of possible responses as they are returned from executing this
     * operation.
     *
     * Generated from protobuf field <code>map<string, .grpc.gateway.protoc_gen_openapiv2.options.Response> responses = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * The list of possible responses as they are returned from executing this
     * operation.
     *
     * Generated from protobuf field <code>map<string, .grpc.gateway.protoc_gen_openapiv2.options.Response> responses = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setResponses($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Gateway\Protoc_gen_openapiv2\Options\Response::class);
        $this->responses = $arr;

        return $this;
    }

    /**
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     *
     * Generated from protobuf field <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSchemes()
    {
        return $this->schemes;
    }

    /**
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     *
     * Generated from protobuf field <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSchemes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Grpc\Gateway\Protoc_gen_openapiv2\Options\Scheme::class);
        $this->schemes = $arr;

        return $this;
    }

    /**
     * Declares this operation to be deprecated. Usage of the declared operation
     * should be refrained. Default value is false.
     *
     * Generated from protobuf field <code>bool deprecated = 11;</code>
     * @return bool
     */
    public function getDeprecated()
    {
        return $this->deprecated;
    }

    /**
     * Declares this operation to be deprecated. Usage of the declared operation
     * should be refrained. Default value is false.
     *
     * Generated from protobuf field <code>bool deprecated = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeprecated($var)
    {
        GPBUtil::checkBool($var);
        $this->deprecated = $var;

        return $this;
    }

    /**
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     *
     * Generated from protobuf field <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSecurity()
    {
        return $this->security;
    }

    /**
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     *
     * Generated from protobuf field <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param array<\Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityRequirement>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSecurity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityRequirement::class);
        $this->security = $arr;

        return $this;
    }

    /**
     * Custom properties that start with "x-" such as "x-foo" used to describe
     * extra functionality that is not covered by the standard OpenAPI Specification.
     * See: https://swagger.io/docs/specification/2-0/swagger-extensions/
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> extensions = 13;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * Custom properties that start with "x-" such as "x-foo" used to describe
     * extra functionality that is not covered by the standard OpenAPI Specification.
     * See: https://swagger.io/docs/specification/2-0/swagger-extensions/
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> extensions = 13;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setExtensions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Value::class);
        $this->extensions = $arr;

        return $this;
    }

    /**
     * Custom parameters such as HTTP request headers.
     * See: https://swagger.io/docs/specification/2-0/describing-parameters/
     * and https://swagger.io/specification/v2/#parameter-object.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.Parameters parameters = 14;</code>
     * @return \Grpc\Gateway\Protoc_gen_openapiv2\Options\Parameters|null
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    public function hasParameters()
    {
        return isset($this->parameters);
    }

    public function clearParameters()
    {
        unset($this->parameters);
    }

    /**
     * Custom parameters such as HTTP request headers.
     * See: https://swagger.io/docs/specification/2-0/describing-parameters/
     * and https://swagger.io/specification/v2/#parameter-object.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.Parameters parameters = 14;</code>
     * @param \Grpc\Gateway\Protoc_gen_openapiv2\Options\Parameters $var
     * @return $this
     */
    public function setParameters($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Gateway\Protoc_gen_openapiv2\Options\Parameters::class);
        $this->parameters = $var;

        return $this;
    }

}

