<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protoc-gen-openapiv2/options/openapiv2.proto

namespace Grpc\Gateway\Protoc_gen_openapiv2\Options;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * `SecurityScheme` is a representation of OpenAPI v2 specification's
 * Security Scheme object.
 * See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#securitySchemeObject
 * Allows the definition of a security scheme that can be used by the
 * operations. Supported schemes are basic authentication, an API key (either as
 * a header or as a query parameter) and OAuth2's common flows (implicit,
 * password, application and access code).
 *
 * Generated from protobuf message <code>grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme</code>
 */
class SecurityScheme extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of the security scheme. Valid values are "basic",
     * "apiKey" or "oauth2".
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Type type = 1;</code>
     */
    protected $type = 0;
    /**
     * A short description for security scheme.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * The name of the header or query parameter to be used.
     * Valid for apiKey.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * The location of the API key. Valid values are "query" or
     * "header".
     * Valid for apiKey.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.In in = 4;</code>
     */
    protected $in = 0;
    /**
     * The flow used by the OAuth2 security scheme. Valid values are
     * "implicit", "password", "application" or "accessCode".
     * Valid for oauth2.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Flow flow = 5;</code>
     */
    protected $flow = 0;
    /**
     * The authorization URL to be used for this flow. This SHOULD be in
     * the form of a URL.
     * Valid for oauth2/implicit and oauth2/accessCode.
     *
     * Generated from protobuf field <code>string authorization_url = 6;</code>
     */
    protected $authorization_url = '';
    /**
     * The token URL to be used for this flow. This SHOULD be in the
     * form of a URL.
     * Valid for oauth2/password, oauth2/application and oauth2/accessCode.
     *
     * Generated from protobuf field <code>string token_url = 7;</code>
     */
    protected $token_url = '';
    /**
     * The available scopes for the OAuth2 security scheme.
     * Valid for oauth2.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.Scopes scopes = 8;</code>
     */
    protected $scopes = null;
    /**
     * Custom properties that start with "x-" such as "x-foo" used to describe
     * extra functionality that is not covered by the standard OpenAPI Specification.
     * See: https://swagger.io/docs/specification/2-0/swagger-extensions/
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> extensions = 9;</code>
     */
    private $extensions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           The type of the security scheme. Valid values are "basic",
     *           "apiKey" or "oauth2".
     *     @type string $description
     *           A short description for security scheme.
     *     @type string $name
     *           The name of the header or query parameter to be used.
     *           Valid for apiKey.
     *     @type int $in
     *           The location of the API key. Valid values are "query" or
     *           "header".
     *           Valid for apiKey.
     *     @type int $flow
     *           The flow used by the OAuth2 security scheme. Valid values are
     *           "implicit", "password", "application" or "accessCode".
     *           Valid for oauth2.
     *     @type string $authorization_url
     *           The authorization URL to be used for this flow. This SHOULD be in
     *           the form of a URL.
     *           Valid for oauth2/implicit and oauth2/accessCode.
     *     @type string $token_url
     *           The token URL to be used for this flow. This SHOULD be in the
     *           form of a URL.
     *           Valid for oauth2/password, oauth2/application and oauth2/accessCode.
     *     @type \Grpc\Gateway\Protoc_gen_openapiv2\Options\Scopes $scopes
     *           The available scopes for the OAuth2 security scheme.
     *           Valid for oauth2.
     *     @type array|\Google\Protobuf\Internal\MapField $extensions
     *           Custom properties that start with "x-" such as "x-foo" used to describe
     *           extra functionality that is not covered by the standard OpenAPI Specification.
     *           See: https://swagger.io/docs/specification/2-0/swagger-extensions/
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProtocGenOpenapiv2\Options\Openapiv2::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of the security scheme. Valid values are "basic",
     * "apiKey" or "oauth2".
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * The type of the security scheme. Valid values are "basic",
     * "apiKey" or "oauth2".
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * A short description for security scheme.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * A short description for security scheme.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * The name of the header or query parameter to be used.
     * Valid for apiKey.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the header or query parameter to be used.
     * Valid for apiKey.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The location of the API key. Valid values are "query" or
     * "header".
     * Valid for apiKey.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.In in = 4;</code>
     * @return int
     */
    public function getIn()
    {
        return $this->in;
    }

    /**
     * The location of the API key. Valid values are "query" or
     * "header".
     * Valid for apiKey.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.In in = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setIn($var)
    {
        GPBUtil::checkEnum($var, \Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme\In::class);
        $this->in = $var;

        return $this;
    }

    /**
     * The flow used by the OAuth2 security scheme. Valid values are
     * "implicit", "password", "application" or "accessCode".
     * Valid for oauth2.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Flow flow = 5;</code>
     * @return int
     */
    public function getFlow()
    {
        return $this->flow;
    }

    /**
     * The flow used by the OAuth2 security scheme. Valid values are
     * "implicit", "password", "application" or "accessCode".
     * Valid for oauth2.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Flow flow = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFlow($var)
    {
        GPBUtil::checkEnum($var, \Grpc\Gateway\Protoc_gen_openapiv2\Options\SecurityScheme\Flow::class);
        $this->flow = $var;

        return $this;
    }

    /**
     * The authorization URL to be used for this flow. This SHOULD be in
     * the form of a URL.
     * Valid for oauth2/implicit and oauth2/accessCode.
     *
     * Generated from protobuf field <code>string authorization_url = 6;</code>
     * @return string
     */
    public function getAuthorizationUrl()
    {
        return $this->authorization_url;
    }

    /**
     * The authorization URL to be used for this flow. This SHOULD be in
     * the form of a URL.
     * Valid for oauth2/implicit and oauth2/accessCode.
     *
     * Generated from protobuf field <code>string authorization_url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorizationUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->authorization_url = $var;

        return $this;
    }

    /**
     * The token URL to be used for this flow. This SHOULD be in the
     * form of a URL.
     * Valid for oauth2/password, oauth2/application and oauth2/accessCode.
     *
     * Generated from protobuf field <code>string token_url = 7;</code>
     * @return string
     */
    public function getTokenUrl()
    {
        return $this->token_url;
    }

    /**
     * The token URL to be used for this flow. This SHOULD be in the
     * form of a URL.
     * Valid for oauth2/password, oauth2/application and oauth2/accessCode.
     *
     * Generated from protobuf field <code>string token_url = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_url = $var;

        return $this;
    }

    /**
     * The available scopes for the OAuth2 security scheme.
     * Valid for oauth2.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.Scopes scopes = 8;</code>
     * @return \Grpc\Gateway\Protoc_gen_openapiv2\Options\Scopes|null
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    public function hasScopes()
    {
        return isset($this->scopes);
    }

    public function clearScopes()
    {
        unset($this->scopes);
    }

    /**
     * The available scopes for the OAuth2 security scheme.
     * Valid for oauth2.
     *
     * Generated from protobuf field <code>.grpc.gateway.protoc_gen_openapiv2.options.Scopes scopes = 8;</code>
     * @param \Grpc\Gateway\Protoc_gen_openapiv2\Options\Scopes $var
     * @return $this
     */
    public function setScopes($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Gateway\Protoc_gen_openapiv2\Options\Scopes::class);
        $this->scopes = $var;

        return $this;
    }

    /**
     * Custom properties that start with "x-" such as "x-foo" used to describe
     * extra functionality that is not covered by the standard OpenAPI Specification.
     * See: https://swagger.io/docs/specification/2-0/swagger-extensions/
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> extensions = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * Custom properties that start with "x-" such as "x-foo" used to describe
     * extra functionality that is not covered by the standard OpenAPI Specification.
     * See: https://swagger.io/docs/specification/2-0/swagger-extensions/
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> extensions = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setExtensions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Value::class);
        $this->extensions = $arr;

        return $this;
    }

}

