<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/event_tickets/ticket_type.proto

namespace Event_tickets;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_tickets.GetByUidRequest</code>
 */
class GetByUidRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The production id of the ticket type.
     *
     * Generated from protobuf field <code>string productionId = 1;</code>
     */
    protected $productionId = '';
    /**
     * User defined id of the ticket type.
     *
     * Generated from protobuf field <code>string uid = 2;</code>
     */
    protected $uid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $productionId
     *           The production id of the ticket type.
     *     @type string $uid
     *           User defined id of the ticket type.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\EventTickets\TicketType::initOnce();
        parent::__construct($data);
    }

    /**
     * The production id of the ticket type.
     *
     * Generated from protobuf field <code>string productionId = 1;</code>
     * @return string
     */
    public function getProductionId()
    {
        return $this->productionId;
    }

    /**
     * The production id of the ticket type.
     *
     * Generated from protobuf field <code>string productionId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProductionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->productionId = $var;

        return $this;
    }

    /**
     * User defined id of the ticket type.
     *
     * Generated from protobuf field <code>string uid = 2;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * User defined id of the ticket type.
     *
     * Generated from protobuf field <code>string uid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;

        return $this;
    }

}

