<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/core/a_rpc_messages.proto

namespace GPBMetadata\Io\Core;

class ARpcMessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Io\Common\CommonObjects::initOnce();
        \GPBMetadata\Io\Common\Message::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ô
io/core/a_rpc_messages.protoiogoogle/protobuf/empty.proto.protoc-gen-openapiv2/options/annotations.protoio/common/common_objects.protoio/common/message.proto2Ø
Messageso

getMessage.io.Id.io.Message"L‚Óä“/message/{id}’A4Get message%Gets an single message by message id.–
createMessage.io.Message.io.Id"p‚Óä“"/message:*’AZCreate MessageCreates a new message.J0
400)
\'There is a problem with the input data.¤
updateMessage.io.Message.google.protobuf.Empty"n‚Óä“/message/{id}:*’ASUpdate MessageUpdate message.J0
400)
\'There is a problem with the input data.´
deleteMessage.io.Id.google.protobuf.Empty"‚‚Óä“*/message/{id}’AjDelete Message2Deleting a message will remove it from all passes.J$
404
Message could not be found.ã
sendMessage.io.SendMessageRequest.io.SendMessageResponse"¢‚Óä“"/message/send:*’A†Send MessageDSends a message to an array of passIds, or to every pass in a class.J0
400)
\'There is a problem with the input data.BG
com.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/ioªPassKit.Grpcbproto3'
        , true);

        static::$is_initialized = true;
    }
}

