<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/single_use_coupons/offer.proto

namespace Single_use_coupons;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>single_use_coupons.CustomerInitiatedCodeProvideOnRedeemSettings</code>
 */
class CustomerInitiatedCodeProvideOnRedeemSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional array of valid codes that can be input on redemption.
     *
     * Generated from protobuf field <code>repeated string validCodes = 1;</code>
     */
    private $validCodes;
    /**
     * Input field box for entering the redemption code.
     *
     * Generated from protobuf field <code>.single_use_coupons.InputField redemptionCodeInput = 2;</code>
     */
    protected $redemptionCodeInput = null;
    /**
     * Submit button to confirm the validation code.
     *
     * Generated from protobuf field <code>string submitButtonText = 3;</code>
     */
    protected $submitButtonText = '';
    /**
     * Localized submit button text.
     *
     * Generated from protobuf field <code>.io.LocalizedString localizedSubmitButtonText = 4;</code>
     */
    protected $localizedSubmitButtonText = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $validCodes
     *           Optional array of valid codes that can be input on redemption.
     *     @type \Single_use_coupons\InputField $redemptionCodeInput
     *           Input field box for entering the redemption code.
     *     @type string $submitButtonText
     *           Submit button to confirm the validation code.
     *     @type \Io\LocalizedString $localizedSubmitButtonText
     *           Localized submit button text.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\SingleUseCoupons\Offer::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional array of valid codes that can be input on redemption.
     *
     * Generated from protobuf field <code>repeated string validCodes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValidCodes()
    {
        return $this->validCodes;
    }

    /**
     * Optional array of valid codes that can be input on redemption.
     *
     * Generated from protobuf field <code>repeated string validCodes = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValidCodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->validCodes = $arr;

        return $this;
    }

    /**
     * Input field box for entering the redemption code.
     *
     * Generated from protobuf field <code>.single_use_coupons.InputField redemptionCodeInput = 2;</code>
     * @return \Single_use_coupons\InputField|null
     */
    public function getRedemptionCodeInput()
    {
        return $this->redemptionCodeInput;
    }

    public function hasRedemptionCodeInput()
    {
        return isset($this->redemptionCodeInput);
    }

    public function clearRedemptionCodeInput()
    {
        unset($this->redemptionCodeInput);
    }

    /**
     * Input field box for entering the redemption code.
     *
     * Generated from protobuf field <code>.single_use_coupons.InputField redemptionCodeInput = 2;</code>
     * @param \Single_use_coupons\InputField $var
     * @return $this
     */
    public function setRedemptionCodeInput($var)
    {
        GPBUtil::checkMessage($var, \Single_use_coupons\InputField::class);
        $this->redemptionCodeInput = $var;

        return $this;
    }

    /**
     * Submit button to confirm the validation code.
     *
     * Generated from protobuf field <code>string submitButtonText = 3;</code>
     * @return string
     */
    public function getSubmitButtonText()
    {
        return $this->submitButtonText;
    }

    /**
     * Submit button to confirm the validation code.
     *
     * Generated from protobuf field <code>string submitButtonText = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSubmitButtonText($var)
    {
        GPBUtil::checkString($var, True);
        $this->submitButtonText = $var;

        return $this;
    }

    /**
     * Localized submit button text.
     *
     * Generated from protobuf field <code>.io.LocalizedString localizedSubmitButtonText = 4;</code>
     * @return \Io\LocalizedString|null
     */
    public function getLocalizedSubmitButtonText()
    {
        return $this->localizedSubmitButtonText;
    }

    public function hasLocalizedSubmitButtonText()
    {
        return isset($this->localizedSubmitButtonText);
    }

    public function clearLocalizedSubmitButtonText()
    {
        unset($this->localizedSubmitButtonText);
    }

    /**
     * Localized submit button text.
     *
     * Generated from protobuf field <code>.io.LocalizedString localizedSubmitButtonText = 4;</code>
     * @param \Io\LocalizedString $var
     * @return $this
     */
    public function setLocalizedSubmitButtonText($var)
    {
        GPBUtil::checkMessage($var, \Io\LocalizedString::class);
        $this->localizedSubmitButtonText = $var;

        return $this;
    }

}

