<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/raw/pass.proto

namespace Raw;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>raw.ListPassesByPassProjectRequest</code>
 */
class ListPassesByPassProjectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string passProjectId = 1;</code>
     */
    protected $passProjectId = '';
    /**
     * Generated from protobuf field <code>.io.Filters filters = 2;</code>
     */
    protected $filters = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $passProjectId
     *     @type \Io\Filters $filters
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Raw\Pass::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string passProjectId = 1;</code>
     * @return string
     */
    public function getPassProjectId()
    {
        return $this->passProjectId;
    }

    /**
     * Generated from protobuf field <code>string passProjectId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPassProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->passProjectId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.Filters filters = 2;</code>
     * @return \Io\Filters|null
     */
    public function getFilters()
    {
        return $this->filters;
    }

    public function hasFilters()
    {
        return isset($this->filters);
    }

    public function clearFilters()
    {
        unset($this->filters);
    }

    /**
     * Generated from protobuf field <code>.io.Filters filters = 2;</code>
     * @param \Io\Filters $var
     * @return $this
     */
    public function setFilters($var)
    {
        GPBUtil::checkMessage($var, \Io\Filters::class);
        $this->filters = $var;

        return $this;
    }

}

