<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ct/scheduler/scheduler.proto

namespace Ct;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ct.JobHistory</code>
 */
class JobHistory extends \Google\Protobuf\Internal\Message
{
    /**
     * Job history id.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Job ID.
     *
     * Generated from protobuf field <code>string jobId = 2;</code>
     */
    protected $jobId = '';
    /**
     * True if the job has succeeded. False if the job has failed.
     *
     * Generated from protobuf field <code>bool success = 3;</code>
     */
    protected $success = false;
    /**
     * The job output log.
     *
     * Generated from protobuf field <code>string log = 4;</code>
     */
    protected $log = '';
    /**
     * The status code.
     *
     * Generated from protobuf field <code>uint32 statusCode = 5;</code>
     */
    protected $statusCode = 0;
    /**
     * Scheduled run datetime for the job.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduledRunDateTime = 6;</code>
     */
    protected $scheduledRunDateTime = null;
    /**
     * Job completion datetime.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp completedAt = 7;</code>
     */
    protected $completedAt = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Job history id.
     *     @type string $jobId
     *           Job ID.
     *     @type bool $success
     *           True if the job has succeeded. False if the job has failed.
     *     @type string $log
     *           The job output log.
     *     @type int $statusCode
     *           The status code.
     *     @type \Google\Protobuf\Timestamp $scheduledRunDateTime
     *           Scheduled run datetime for the job.
     *     @type \Google\Protobuf\Timestamp $completedAt
     *           Job completion datetime.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ct\Scheduler\Scheduler::initOnce();
        parent::__construct($data);
    }

    /**
     * Job history id.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Job history id.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Job ID.
     *
     * Generated from protobuf field <code>string jobId = 2;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->jobId;
    }

    /**
     * Job ID.
     *
     * Generated from protobuf field <code>string jobId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, True);
        $this->jobId = $var;

        return $this;
    }

    /**
     * True if the job has succeeded. False if the job has failed.
     *
     * Generated from protobuf field <code>bool success = 3;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * True if the job has succeeded. False if the job has failed.
     *
     * Generated from protobuf field <code>bool success = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * The job output log.
     *
     * Generated from protobuf field <code>string log = 4;</code>
     * @return string
     */
    public function getLog()
    {
        return $this->log;
    }

    /**
     * The job output log.
     *
     * Generated from protobuf field <code>string log = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLog($var)
    {
        GPBUtil::checkString($var, True);
        $this->log = $var;

        return $this;
    }

    /**
     * The status code.
     *
     * Generated from protobuf field <code>uint32 statusCode = 5;</code>
     * @return int
     */
    public function getStatusCode()
    {
        return $this->statusCode;
    }

    /**
     * The status code.
     *
     * Generated from protobuf field <code>uint32 statusCode = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStatusCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->statusCode = $var;

        return $this;
    }

    /**
     * Scheduled run datetime for the job.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduledRunDateTime = 6;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getScheduledRunDateTime()
    {
        return $this->scheduledRunDateTime;
    }

    public function hasScheduledRunDateTime()
    {
        return isset($this->scheduledRunDateTime);
    }

    public function clearScheduledRunDateTime()
    {
        unset($this->scheduledRunDateTime);
    }

    /**
     * Scheduled run datetime for the job.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp scheduledRunDateTime = 6;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setScheduledRunDateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->scheduledRunDateTime = $var;

        return $this;
    }

    /**
     * Job completion datetime.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp completedAt = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCompletedAt()
    {
        return $this->completedAt;
    }

    public function hasCompletedAt()
    {
        return isset($this->completedAt);
    }

    public function clearCompletedAt()
    {
        unset($this->completedAt);
    }

    /**
     * Job completion datetime.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp completedAt = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCompletedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->completedAt = $var;

        return $this;
    }

}

