<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/flights/airport.proto

namespace Flights;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Airport Request is used for retrieving or deleting a port record.
 *
 * Generated from protobuf message <code>flights.AirportCode</code>
 */
class AirportCode extends \Google\Protobuf\Internal\Message
{
    /**
     * The IATA or ICAO airport code.
     *
     * Generated from protobuf field <code>string airportCode = 1;</code>
     */
    protected $airportCode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $airportCode
     *           The IATA or ICAO airport code.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Flights\Airport::initOnce();
        parent::__construct($data);
    }

    /**
     * The IATA or ICAO airport code.
     *
     * Generated from protobuf field <code>string airportCode = 1;</code>
     * @return string
     */
    public function getAirportCode()
    {
        return $this->airportCode;
    }

    /**
     * The IATA or ICAO airport code.
     *
     * Generated from protobuf field <code>string airportCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAirportCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->airportCode = $var;

        return $this;
    }

}

