<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/flights/carrier.proto

namespace Flights;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * CarrierCode is used for retrieving or deleting a port record.
 *
 * Generated from protobuf message <code>flights.CarrierCode</code>
 */
class CarrierCode extends \Google\Protobuf\Internal\Message
{
    /**
     * The IATA or ICAO carrier code.
     *
     * Generated from protobuf field <code>string carrierCode = 1;</code>
     */
    protected $carrierCode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $carrierCode
     *           The IATA or ICAO carrier code.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Flights\Carrier::initOnce();
        parent::__construct($data);
    }

    /**
     * The IATA or ICAO carrier code.
     *
     * Generated from protobuf field <code>string carrierCode = 1;</code>
     * @return string
     */
    public function getCarrierCode()
    {
        return $this->carrierCode;
    }

    /**
     * The IATA or ICAO carrier code.
     *
     * Generated from protobuf field <code>string carrierCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrierCode = $var;

        return $this;
    }

}

