<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/flights/flight.proto

namespace Flights;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A Flight Request message is used to retrieve or identify an individual flight operation. For direct flights with multiple stops, a segment number or departure point is required.
 *
 * Generated from protobuf message <code>flights.FlightRequest</code>
 */
class FlightRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The 2 character IATA code or 3 character ICAO code.
     *
     * Generated from protobuf field <code>string carrierCode = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $carrierCode = '';
    /**
     * The flight number.
     *
     * Generated from protobuf field <code>string flightNumber = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $flightNumber = '';
    /**
     * The scheduled date of the flight, stated in the timezone of the boarding point.
     *
     * Generated from protobuf field <code>.io.Date departureDate = 3;</code>
     */
    protected $departureDate = null;
    /**
     * The IATA airport code for the boarding point of the flight. Only required for direct flights with stops where the boarding point is after the first port and segment is not provided.
     *
     * Generated from protobuf field <code>string boardingPoint = 5;</code>
     */
    protected $boardingPoint = '';
    /**
     * The IATA airport code for the destination of the flight. Only required for direct flights with stops where the flight ends before the final port.
     *
     * Generated from protobuf field <code>string deplaningPoint = 6;</code>
     */
    protected $deplaningPoint = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $carrierCode
     *           The 2 character IATA code or 3 character ICAO code.
     *     @type string $flightNumber
     *           The flight number.
     *     @type \Io\Date $departureDate
     *           The scheduled date of the flight, stated in the timezone of the boarding point.
     *     @type string $boardingPoint
     *           The IATA airport code for the boarding point of the flight. Only required for direct flights with stops where the boarding point is after the first port and segment is not provided.
     *     @type string $deplaningPoint
     *           The IATA airport code for the destination of the flight. Only required for direct flights with stops where the flight ends before the final port.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Flights\Flight::initOnce();
        parent::__construct($data);
    }

    /**
     * The 2 character IATA code or 3 character ICAO code.
     *
     * Generated from protobuf field <code>string carrierCode = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getCarrierCode()
    {
        return $this->carrierCode;
    }

    /**
     * The 2 character IATA code or 3 character ICAO code.
     *
     * Generated from protobuf field <code>string carrierCode = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrierCode = $var;

        return $this;
    }

    /**
     * The flight number.
     *
     * Generated from protobuf field <code>string flightNumber = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getFlightNumber()
    {
        return $this->flightNumber;
    }

    /**
     * The flight number.
     *
     * Generated from protobuf field <code>string flightNumber = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setFlightNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->flightNumber = $var;

        return $this;
    }

    /**
     * The scheduled date of the flight, stated in the timezone of the boarding point.
     *
     * Generated from protobuf field <code>.io.Date departureDate = 3;</code>
     * @return \Io\Date|null
     */
    public function getDepartureDate()
    {
        return $this->departureDate;
    }

    public function hasDepartureDate()
    {
        return isset($this->departureDate);
    }

    public function clearDepartureDate()
    {
        unset($this->departureDate);
    }

    /**
     * The scheduled date of the flight, stated in the timezone of the boarding point.
     *
     * Generated from protobuf field <code>.io.Date departureDate = 3;</code>
     * @param \Io\Date $var
     * @return $this
     */
    public function setDepartureDate($var)
    {
        GPBUtil::checkMessage($var, \Io\Date::class);
        $this->departureDate = $var;

        return $this;
    }

    /**
     * The IATA airport code for the boarding point of the flight. Only required for direct flights with stops where the boarding point is after the first port and segment is not provided.
     *
     * Generated from protobuf field <code>string boardingPoint = 5;</code>
     * @return string
     */
    public function getBoardingPoint()
    {
        return $this->boardingPoint;
    }

    /**
     * The IATA airport code for the boarding point of the flight. Only required for direct flights with stops where the boarding point is after the first port and segment is not provided.
     *
     * Generated from protobuf field <code>string boardingPoint = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBoardingPoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->boardingPoint = $var;

        return $this;
    }

    /**
     * The IATA airport code for the destination of the flight. Only required for direct flights with stops where the flight ends before the final port.
     *
     * Generated from protobuf field <code>string deplaningPoint = 6;</code>
     * @return string
     */
    public function getDeplaningPoint()
    {
        return $this->deplaningPoint;
    }

    /**
     * The IATA airport code for the destination of the flight. Only required for direct flights with stops where the flight ends before the final port.
     *
     * Generated from protobuf field <code>string deplaningPoint = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDeplaningPoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->deplaningPoint = $var;

        return $this;
    }

}

