<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/flights/flight.proto

namespace Flights;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flights.Flight</code>
 */
class Flight extends \Google\Protobuf\Internal\Message
{
    /**
     * The IATA or ICAO carrier code for the flight. In the case of a code-share, this should be the carrier code that you wish to present to the customer. This could be the marketing code, or the operating airline code. A carrier record for this code must exist.
     *
     * Generated from protobuf field <code>string carrierCode = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $carrierCode = '';
    /**
     * The flight number.
     *
     * Generated from protobuf field <code>string flightNumber = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $flightNumber = '';
    /**
     * The IATA airport code of the boarding point. Only required is segment is not provided.
     *
     * Generated from protobuf field <code>string boardingPoint = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $boardingPoint = '';
    /**
     * The IATA airport code of the deplaning point.
     *
     * Generated from protobuf field <code>string deplaningPoint = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $deplaningPoint = '';
    /**
     * The scheduled date of departure.
     *
     * Generated from protobuf field <code>.io.Date departureDate = 5;</code>
     */
    protected $departureDate = null;
    /**
     * Departure Terminal.
     *
     * Generated from protobuf field <code>string departureTerminal = 6;</code>
     */
    protected $departureTerminal = '';
    /**
     * Arrival Terminal.
     *
     * Generated from protobuf field <code>string arrivalTerminal = 7;</code>
     */
    protected $arrivalTerminal = '';
    /**
     * Departure Gate.
     *
     * Generated from protobuf field <code>string departureGate = 8;</code>
     */
    protected $departureGate = '';
    /**
     * Arrival Gate.
     *
     * Generated from protobuf field <code>string arrivalGate = 9;</code>
     */
    protected $arrivalGate = '';
    /**
     * The scheduled departure time. If omitted then the departureDate must be specified.
     *
     * Generated from protobuf field <code>.io.LocalDateTime scheduledDepartureTime = 10;</code>
     */
    protected $scheduledDepartureTime = null;
    /**
     * The estimated departure time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime estimatedDepartureTime = 11;</code>
     */
    protected $estimatedDepartureTime = null;
    /**
     * The boarding time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime boardingTime = 12;</code>
     */
    protected $boardingTime = null;
    /**
     * The time the gate will close.
     *
     * Generated from protobuf field <code>.io.LocalDateTime gateClosingTime = 13;</code>
     */
    protected $gateClosingTime = null;
    /**
     * The scheduled arrival time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime scheduledArrivalTime = 14;</code>
     */
    protected $scheduledArrivalTime = null;
    /**
     * The estimated arrival time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime estimatedArrivalTime = 15;</code>
     */
    protected $estimatedArrivalTime = null;
    /**
     * If the flight is operated by a carrier other than the carrierCode supplied, provide the IATA or ICAO carrier code for the operating carrier.  A carrier record must exist.
     *
     * Generated from protobuf field <code>string operatingCarrierCode = 16 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $operatingCarrierCode = '';
    /**
     * If the flight is operated by a carrier other than the carrierCode supplied, provide the flight number for the operating carrier.
     *
     * Generated from protobuf field <code>string operatingFlightNumber = 17 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $operatingFlightNumber = '';
    /**
     * If the flight has code shares, then enter the carrier code and flight number. If there is an operating carrier, then do not include this in the list. Code share carriers will not be validated.
     *
     * Generated from protobuf field <code>repeated string codeShareFlightNumbers = 18;</code>
     */
    private $codeShareFlightNumbers;
    /**
     * The pass template id.
     *
     * Generated from protobuf field <code>string passTemplateId = 19;</code>
     */
    protected $passTemplateId = '';
    /**
     * The baggage belt at the destination.
     *
     * Generated from protobuf field <code>string baggageBelt = 21;</code>
     */
    protected $baggageBelt = '';
    /**
     * Minutes after estimated or scheduled arrival to automatically invalidate the pass. Enter a value of 9999999 or greater if the pass should not auto invalidate. Default is 48 hours.
     *
     * Generated from protobuf field <code>uint32 autoInvalidateAfter = 22 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $autoInvalidateAfter = 0;
    /**
     * Deprecated: Use InvalidateCancelledPasses.
     *
     * Generated from protobuf field <code>bool autoInvalidateCancelledPasses = 23 [deprecated = true];</code>
     * @deprecated
     */
    protected $autoInvalidateCancelledPasses = false;
    /**
     * A list of up to 10 GPS locations where this boarding pass should be presented on the lock-screen. Values here will override the designated defaults.
     *
     * Generated from protobuf field <code>repeated .io.GPSLocation locationMessages = 24 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $locationMessages;
    /**
     * A list of up to 10 Beacon UUIDs that should trigger the boarding pass to be presented on the lock-screen. Values here will override the designated defaults.
     *
     * Generated from protobuf field <code>repeated .io.Beacon beaconMessages = 25 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $beaconMessages;
    /**
     * A list of links to be appended to the end of each boarding pass.
     *
     * Generated from protobuf field <code>repeated .io.Link links = 26 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $links;
    /**
     * Suspend automatic updates to all boarding passes for this flight.
     *
     * Generated from protobuf field <code>bool suspendAutomaticUpdates = 27;</code>
     */
    protected $suspendAutomaticUpdates = false;
    /**
     * Used to determine the label printed above the boarding group on the Google Pay pass.
     *
     * Generated from protobuf field <code>.flights.BoardingPolicy boardingPolicy = 28;</code>
     */
    protected $boardingPolicy = 0;
    /**
     * Used to determine the label printed above the seat class on the Google Pay pass. E.g. Economy, Economy Plus.
     *
     * Generated from protobuf field <code>.flights.SeatClassPolicy seatingPolicy = 29;</code>
     */
    protected $seatingPolicy = 0;
    /**
     * The status of the flight. This can be manually set, or automatically set for customers subscribing to automatic updates.
     *
     * Generated from protobuf field <code>.flights.FlightStatus status = 30;</code>
     */
    protected $status = 0;
    /**
     * If PassKit are generating barcodes, include conditional items. Default false.
     *
     * Generated from protobuf field <code>bool ConditionalItems = 31;</code>
     */
    protected $ConditionalItems = false;
    /**
     * If PassKit are generating barcodes, default airline use data (IATA item 4). This can be overwritten at the flight and boarding pass level.
     *
     * Generated from protobuf field <code>string BarcodeAdditionalData = 32;</code>
     */
    protected $BarcodeAdditionalData = '';
    /**
     * Issued, installed, uninstalled and invalidated counts. Metrics are not writable.
     *
     * Generated from protobuf field <code>.io.Metrics metrics = 33;</code>
     */
    protected $metrics = null;
    /**
     * How the flight was created Create mode, manually or automatically.
     *
     * Generated from protobuf field <code>.flights.FlightCreateMode createMethod = 34;</code>
     */
    protected $createMethod = 0;
    /**
     * For automatically created flights, shows the ID of the designator that bootstrapped the flight record.
     *
     * Generated from protobuf field <code>string designatorId = 35;</code>
     */
    protected $designatorId = '';
    /**
     * Invalidate passes where either the booking or the flight have been cancelled. Default is ON.
     *
     * Generated from protobuf field <code>.io.Toggle invalidateCancelledPasses = 36 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $invalidateCancelledPasses = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $carrierCode
     *           The IATA or ICAO carrier code for the flight. In the case of a code-share, this should be the carrier code that you wish to present to the customer. This could be the marketing code, or the operating airline code. A carrier record for this code must exist.
     *     @type string $flightNumber
     *           The flight number.
     *     @type string $boardingPoint
     *           The IATA airport code of the boarding point. Only required is segment is not provided.
     *     @type string $deplaningPoint
     *           The IATA airport code of the deplaning point.
     *     @type \Io\Date $departureDate
     *           The scheduled date of departure.
     *     @type string $departureTerminal
     *           Departure Terminal.
     *     @type string $arrivalTerminal
     *           Arrival Terminal.
     *     @type string $departureGate
     *           Departure Gate.
     *     @type string $arrivalGate
     *           Arrival Gate.
     *     @type \Io\LocalDateTime $scheduledDepartureTime
     *           The scheduled departure time. If omitted then the departureDate must be specified.
     *     @type \Io\LocalDateTime $estimatedDepartureTime
     *           The estimated departure time.
     *     @type \Io\LocalDateTime $boardingTime
     *           The boarding time.
     *     @type \Io\LocalDateTime $gateClosingTime
     *           The time the gate will close.
     *     @type \Io\LocalDateTime $scheduledArrivalTime
     *           The scheduled arrival time.
     *     @type \Io\LocalDateTime $estimatedArrivalTime
     *           The estimated arrival time.
     *     @type string $operatingCarrierCode
     *           If the flight is operated by a carrier other than the carrierCode supplied, provide the IATA or ICAO carrier code for the operating carrier.  A carrier record must exist.
     *     @type string $operatingFlightNumber
     *           If the flight is operated by a carrier other than the carrierCode supplied, provide the flight number for the operating carrier.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $codeShareFlightNumbers
     *           If the flight has code shares, then enter the carrier code and flight number. If there is an operating carrier, then do not include this in the list. Code share carriers will not be validated.
     *     @type string $passTemplateId
     *           The pass template id.
     *     @type string $baggageBelt
     *           The baggage belt at the destination.
     *     @type int $autoInvalidateAfter
     *           Minutes after estimated or scheduled arrival to automatically invalidate the pass. Enter a value of 9999999 or greater if the pass should not auto invalidate. Default is 48 hours.
     *     @type bool $autoInvalidateCancelledPasses
     *           Deprecated: Use InvalidateCancelledPasses.
     *     @type array<\Io\GPSLocation>|\Google\Protobuf\Internal\RepeatedField $locationMessages
     *           A list of up to 10 GPS locations where this boarding pass should be presented on the lock-screen. Values here will override the designated defaults.
     *     @type array<\Io\Beacon>|\Google\Protobuf\Internal\RepeatedField $beaconMessages
     *           A list of up to 10 Beacon UUIDs that should trigger the boarding pass to be presented on the lock-screen. Values here will override the designated defaults.
     *     @type array<\Io\Link>|\Google\Protobuf\Internal\RepeatedField $links
     *           A list of links to be appended to the end of each boarding pass.
     *     @type bool $suspendAutomaticUpdates
     *           Suspend automatic updates to all boarding passes for this flight.
     *     @type int $boardingPolicy
     *           Used to determine the label printed above the boarding group on the Google Pay pass.
     *     @type int $seatingPolicy
     *           Used to determine the label printed above the seat class on the Google Pay pass. E.g. Economy, Economy Plus.
     *     @type int $status
     *           The status of the flight. This can be manually set, or automatically set for customers subscribing to automatic updates.
     *     @type bool $ConditionalItems
     *           If PassKit are generating barcodes, include conditional items. Default false.
     *     @type string $BarcodeAdditionalData
     *           If PassKit are generating barcodes, default airline use data (IATA item 4). This can be overwritten at the flight and boarding pass level.
     *     @type \Io\Metrics $metrics
     *           Issued, installed, uninstalled and invalidated counts. Metrics are not writable.
     *     @type int $createMethod
     *           How the flight was created Create mode, manually or automatically.
     *     @type string $designatorId
     *           For automatically created flights, shows the ID of the designator that bootstrapped the flight record.
     *     @type int $invalidateCancelledPasses
     *           Invalidate passes where either the booking or the flight have been cancelled. Default is ON.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Flights\Flight::initOnce();
        parent::__construct($data);
    }

    /**
     * The IATA or ICAO carrier code for the flight. In the case of a code-share, this should be the carrier code that you wish to present to the customer. This could be the marketing code, or the operating airline code. A carrier record for this code must exist.
     *
     * Generated from protobuf field <code>string carrierCode = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getCarrierCode()
    {
        return $this->carrierCode;
    }

    /**
     * The IATA or ICAO carrier code for the flight. In the case of a code-share, this should be the carrier code that you wish to present to the customer. This could be the marketing code, or the operating airline code. A carrier record for this code must exist.
     *
     * Generated from protobuf field <code>string carrierCode = 1 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrierCode = $var;

        return $this;
    }

    /**
     * The flight number.
     *
     * Generated from protobuf field <code>string flightNumber = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getFlightNumber()
    {
        return $this->flightNumber;
    }

    /**
     * The flight number.
     *
     * Generated from protobuf field <code>string flightNumber = 2 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setFlightNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->flightNumber = $var;

        return $this;
    }

    /**
     * The IATA airport code of the boarding point. Only required is segment is not provided.
     *
     * Generated from protobuf field <code>string boardingPoint = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getBoardingPoint()
    {
        return $this->boardingPoint;
    }

    /**
     * The IATA airport code of the boarding point. Only required is segment is not provided.
     *
     * Generated from protobuf field <code>string boardingPoint = 3 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setBoardingPoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->boardingPoint = $var;

        return $this;
    }

    /**
     * The IATA airport code of the deplaning point.
     *
     * Generated from protobuf field <code>string deplaningPoint = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getDeplaningPoint()
    {
        return $this->deplaningPoint;
    }

    /**
     * The IATA airport code of the deplaning point.
     *
     * Generated from protobuf field <code>string deplaningPoint = 4 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setDeplaningPoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->deplaningPoint = $var;

        return $this;
    }

    /**
     * The scheduled date of departure.
     *
     * Generated from protobuf field <code>.io.Date departureDate = 5;</code>
     * @return \Io\Date|null
     */
    public function getDepartureDate()
    {
        return $this->departureDate;
    }

    public function hasDepartureDate()
    {
        return isset($this->departureDate);
    }

    public function clearDepartureDate()
    {
        unset($this->departureDate);
    }

    /**
     * The scheduled date of departure.
     *
     * Generated from protobuf field <code>.io.Date departureDate = 5;</code>
     * @param \Io\Date $var
     * @return $this
     */
    public function setDepartureDate($var)
    {
        GPBUtil::checkMessage($var, \Io\Date::class);
        $this->departureDate = $var;

        return $this;
    }

    /**
     * Departure Terminal.
     *
     * Generated from protobuf field <code>string departureTerminal = 6;</code>
     * @return string
     */
    public function getDepartureTerminal()
    {
        return $this->departureTerminal;
    }

    /**
     * Departure Terminal.
     *
     * Generated from protobuf field <code>string departureTerminal = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartureTerminal($var)
    {
        GPBUtil::checkString($var, True);
        $this->departureTerminal = $var;

        return $this;
    }

    /**
     * Arrival Terminal.
     *
     * Generated from protobuf field <code>string arrivalTerminal = 7;</code>
     * @return string
     */
    public function getArrivalTerminal()
    {
        return $this->arrivalTerminal;
    }

    /**
     * Arrival Terminal.
     *
     * Generated from protobuf field <code>string arrivalTerminal = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setArrivalTerminal($var)
    {
        GPBUtil::checkString($var, True);
        $this->arrivalTerminal = $var;

        return $this;
    }

    /**
     * Departure Gate.
     *
     * Generated from protobuf field <code>string departureGate = 8;</code>
     * @return string
     */
    public function getDepartureGate()
    {
        return $this->departureGate;
    }

    /**
     * Departure Gate.
     *
     * Generated from protobuf field <code>string departureGate = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartureGate($var)
    {
        GPBUtil::checkString($var, True);
        $this->departureGate = $var;

        return $this;
    }

    /**
     * Arrival Gate.
     *
     * Generated from protobuf field <code>string arrivalGate = 9;</code>
     * @return string
     */
    public function getArrivalGate()
    {
        return $this->arrivalGate;
    }

    /**
     * Arrival Gate.
     *
     * Generated from protobuf field <code>string arrivalGate = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setArrivalGate($var)
    {
        GPBUtil::checkString($var, True);
        $this->arrivalGate = $var;

        return $this;
    }

    /**
     * The scheduled departure time. If omitted then the departureDate must be specified.
     *
     * Generated from protobuf field <code>.io.LocalDateTime scheduledDepartureTime = 10;</code>
     * @return \Io\LocalDateTime|null
     */
    public function getScheduledDepartureTime()
    {
        return $this->scheduledDepartureTime;
    }

    public function hasScheduledDepartureTime()
    {
        return isset($this->scheduledDepartureTime);
    }

    public function clearScheduledDepartureTime()
    {
        unset($this->scheduledDepartureTime);
    }

    /**
     * The scheduled departure time. If omitted then the departureDate must be specified.
     *
     * Generated from protobuf field <code>.io.LocalDateTime scheduledDepartureTime = 10;</code>
     * @param \Io\LocalDateTime $var
     * @return $this
     */
    public function setScheduledDepartureTime($var)
    {
        GPBUtil::checkMessage($var, \Io\LocalDateTime::class);
        $this->scheduledDepartureTime = $var;

        return $this;
    }

    /**
     * The estimated departure time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime estimatedDepartureTime = 11;</code>
     * @return \Io\LocalDateTime|null
     */
    public function getEstimatedDepartureTime()
    {
        return $this->estimatedDepartureTime;
    }

    public function hasEstimatedDepartureTime()
    {
        return isset($this->estimatedDepartureTime);
    }

    public function clearEstimatedDepartureTime()
    {
        unset($this->estimatedDepartureTime);
    }

    /**
     * The estimated departure time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime estimatedDepartureTime = 11;</code>
     * @param \Io\LocalDateTime $var
     * @return $this
     */
    public function setEstimatedDepartureTime($var)
    {
        GPBUtil::checkMessage($var, \Io\LocalDateTime::class);
        $this->estimatedDepartureTime = $var;

        return $this;
    }

    /**
     * The boarding time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime boardingTime = 12;</code>
     * @return \Io\LocalDateTime|null
     */
    public function getBoardingTime()
    {
        return $this->boardingTime;
    }

    public function hasBoardingTime()
    {
        return isset($this->boardingTime);
    }

    public function clearBoardingTime()
    {
        unset($this->boardingTime);
    }

    /**
     * The boarding time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime boardingTime = 12;</code>
     * @param \Io\LocalDateTime $var
     * @return $this
     */
    public function setBoardingTime($var)
    {
        GPBUtil::checkMessage($var, \Io\LocalDateTime::class);
        $this->boardingTime = $var;

        return $this;
    }

    /**
     * The time the gate will close.
     *
     * Generated from protobuf field <code>.io.LocalDateTime gateClosingTime = 13;</code>
     * @return \Io\LocalDateTime|null
     */
    public function getGateClosingTime()
    {
        return $this->gateClosingTime;
    }

    public function hasGateClosingTime()
    {
        return isset($this->gateClosingTime);
    }

    public function clearGateClosingTime()
    {
        unset($this->gateClosingTime);
    }

    /**
     * The time the gate will close.
     *
     * Generated from protobuf field <code>.io.LocalDateTime gateClosingTime = 13;</code>
     * @param \Io\LocalDateTime $var
     * @return $this
     */
    public function setGateClosingTime($var)
    {
        GPBUtil::checkMessage($var, \Io\LocalDateTime::class);
        $this->gateClosingTime = $var;

        return $this;
    }

    /**
     * The scheduled arrival time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime scheduledArrivalTime = 14;</code>
     * @return \Io\LocalDateTime|null
     */
    public function getScheduledArrivalTime()
    {
        return $this->scheduledArrivalTime;
    }

    public function hasScheduledArrivalTime()
    {
        return isset($this->scheduledArrivalTime);
    }

    public function clearScheduledArrivalTime()
    {
        unset($this->scheduledArrivalTime);
    }

    /**
     * The scheduled arrival time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime scheduledArrivalTime = 14;</code>
     * @param \Io\LocalDateTime $var
     * @return $this
     */
    public function setScheduledArrivalTime($var)
    {
        GPBUtil::checkMessage($var, \Io\LocalDateTime::class);
        $this->scheduledArrivalTime = $var;

        return $this;
    }

    /**
     * The estimated arrival time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime estimatedArrivalTime = 15;</code>
     * @return \Io\LocalDateTime|null
     */
    public function getEstimatedArrivalTime()
    {
        return $this->estimatedArrivalTime;
    }

    public function hasEstimatedArrivalTime()
    {
        return isset($this->estimatedArrivalTime);
    }

    public function clearEstimatedArrivalTime()
    {
        unset($this->estimatedArrivalTime);
    }

    /**
     * The estimated arrival time.
     *
     * Generated from protobuf field <code>.io.LocalDateTime estimatedArrivalTime = 15;</code>
     * @param \Io\LocalDateTime $var
     * @return $this
     */
    public function setEstimatedArrivalTime($var)
    {
        GPBUtil::checkMessage($var, \Io\LocalDateTime::class);
        $this->estimatedArrivalTime = $var;

        return $this;
    }

    /**
     * If the flight is operated by a carrier other than the carrierCode supplied, provide the IATA or ICAO carrier code for the operating carrier.  A carrier record must exist.
     *
     * Generated from protobuf field <code>string operatingCarrierCode = 16 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getOperatingCarrierCode()
    {
        return $this->operatingCarrierCode;
    }

    /**
     * If the flight is operated by a carrier other than the carrierCode supplied, provide the IATA or ICAO carrier code for the operating carrier.  A carrier record must exist.
     *
     * Generated from protobuf field <code>string operatingCarrierCode = 16 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOperatingCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->operatingCarrierCode = $var;

        return $this;
    }

    /**
     * If the flight is operated by a carrier other than the carrierCode supplied, provide the flight number for the operating carrier.
     *
     * Generated from protobuf field <code>string operatingFlightNumber = 17 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getOperatingFlightNumber()
    {
        return $this->operatingFlightNumber;
    }

    /**
     * If the flight is operated by a carrier other than the carrierCode supplied, provide the flight number for the operating carrier.
     *
     * Generated from protobuf field <code>string operatingFlightNumber = 17 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setOperatingFlightNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->operatingFlightNumber = $var;

        return $this;
    }

    /**
     * If the flight has code shares, then enter the carrier code and flight number. If there is an operating carrier, then do not include this in the list. Code share carriers will not be validated.
     *
     * Generated from protobuf field <code>repeated string codeShareFlightNumbers = 18;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCodeShareFlightNumbers()
    {
        return $this->codeShareFlightNumbers;
    }

    /**
     * If the flight has code shares, then enter the carrier code and flight number. If there is an operating carrier, then do not include this in the list. Code share carriers will not be validated.
     *
     * Generated from protobuf field <code>repeated string codeShareFlightNumbers = 18;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCodeShareFlightNumbers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->codeShareFlightNumbers = $arr;

        return $this;
    }

    /**
     * The pass template id.
     *
     * Generated from protobuf field <code>string passTemplateId = 19;</code>
     * @return string
     */
    public function getPassTemplateId()
    {
        return $this->passTemplateId;
    }

    /**
     * The pass template id.
     *
     * Generated from protobuf field <code>string passTemplateId = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setPassTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->passTemplateId = $var;

        return $this;
    }

    /**
     * The baggage belt at the destination.
     *
     * Generated from protobuf field <code>string baggageBelt = 21;</code>
     * @return string
     */
    public function getBaggageBelt()
    {
        return $this->baggageBelt;
    }

    /**
     * The baggage belt at the destination.
     *
     * Generated from protobuf field <code>string baggageBelt = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setBaggageBelt($var)
    {
        GPBUtil::checkString($var, True);
        $this->baggageBelt = $var;

        return $this;
    }

    /**
     * Minutes after estimated or scheduled arrival to automatically invalidate the pass. Enter a value of 9999999 or greater if the pass should not auto invalidate. Default is 48 hours.
     *
     * Generated from protobuf field <code>uint32 autoInvalidateAfter = 22 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int
     */
    public function getAutoInvalidateAfter()
    {
        return $this->autoInvalidateAfter;
    }

    /**
     * Minutes after estimated or scheduled arrival to automatically invalidate the pass. Enter a value of 9999999 or greater if the pass should not auto invalidate. Default is 48 hours.
     *
     * Generated from protobuf field <code>uint32 autoInvalidateAfter = 22 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int $var
     * @return $this
     */
    public function setAutoInvalidateAfter($var)
    {
        GPBUtil::checkUint32($var);
        $this->autoInvalidateAfter = $var;

        return $this;
    }

    /**
     * Deprecated: Use InvalidateCancelledPasses.
     *
     * Generated from protobuf field <code>bool autoInvalidateCancelledPasses = 23 [deprecated = true];</code>
     * @return bool
     * @deprecated
     */
    public function getAutoInvalidateCancelledPasses()
    {
        @trigger_error('autoInvalidateCancelledPasses is deprecated.', E_USER_DEPRECATED);
        return $this->autoInvalidateCancelledPasses;
    }

    /**
     * Deprecated: Use InvalidateCancelledPasses.
     *
     * Generated from protobuf field <code>bool autoInvalidateCancelledPasses = 23 [deprecated = true];</code>
     * @param bool $var
     * @return $this
     * @deprecated
     */
    public function setAutoInvalidateCancelledPasses($var)
    {
        @trigger_error('autoInvalidateCancelledPasses is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkBool($var);
        $this->autoInvalidateCancelledPasses = $var;

        return $this;
    }

    /**
     * A list of up to 10 GPS locations where this boarding pass should be presented on the lock-screen. Values here will override the designated defaults.
     *
     * Generated from protobuf field <code>repeated .io.GPSLocation locationMessages = 24 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocationMessages()
    {
        return $this->locationMessages;
    }

    /**
     * A list of up to 10 GPS locations where this boarding pass should be presented on the lock-screen. Values here will override the designated defaults.
     *
     * Generated from protobuf field <code>repeated .io.GPSLocation locationMessages = 24 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<\Io\GPSLocation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocationMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\GPSLocation::class);
        $this->locationMessages = $arr;

        return $this;
    }

    /**
     * A list of up to 10 Beacon UUIDs that should trigger the boarding pass to be presented on the lock-screen. Values here will override the designated defaults.
     *
     * Generated from protobuf field <code>repeated .io.Beacon beaconMessages = 25 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBeaconMessages()
    {
        return $this->beaconMessages;
    }

    /**
     * A list of up to 10 Beacon UUIDs that should trigger the boarding pass to be presented on the lock-screen. Values here will override the designated defaults.
     *
     * Generated from protobuf field <code>repeated .io.Beacon beaconMessages = 25 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<\Io\Beacon>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBeaconMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Beacon::class);
        $this->beaconMessages = $arr;

        return $this;
    }

    /**
     * A list of links to be appended to the end of each boarding pass.
     *
     * Generated from protobuf field <code>repeated .io.Link links = 26 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLinks()
    {
        return $this->links;
    }

    /**
     * A list of links to be appended to the end of each boarding pass.
     *
     * Generated from protobuf field <code>repeated .io.Link links = 26 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<\Io\Link>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLinks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Link::class);
        $this->links = $arr;

        return $this;
    }

    /**
     * Suspend automatic updates to all boarding passes for this flight.
     *
     * Generated from protobuf field <code>bool suspendAutomaticUpdates = 27;</code>
     * @return bool
     */
    public function getSuspendAutomaticUpdates()
    {
        return $this->suspendAutomaticUpdates;
    }

    /**
     * Suspend automatic updates to all boarding passes for this flight.
     *
     * Generated from protobuf field <code>bool suspendAutomaticUpdates = 27;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuspendAutomaticUpdates($var)
    {
        GPBUtil::checkBool($var);
        $this->suspendAutomaticUpdates = $var;

        return $this;
    }

    /**
     * Used to determine the label printed above the boarding group on the Google Pay pass.
     *
     * Generated from protobuf field <code>.flights.BoardingPolicy boardingPolicy = 28;</code>
     * @return int
     */
    public function getBoardingPolicy()
    {
        return $this->boardingPolicy;
    }

    /**
     * Used to determine the label printed above the boarding group on the Google Pay pass.
     *
     * Generated from protobuf field <code>.flights.BoardingPolicy boardingPolicy = 28;</code>
     * @param int $var
     * @return $this
     */
    public function setBoardingPolicy($var)
    {
        GPBUtil::checkEnum($var, \Flights\BoardingPolicy::class);
        $this->boardingPolicy = $var;

        return $this;
    }

    /**
     * Used to determine the label printed above the seat class on the Google Pay pass. E.g. Economy, Economy Plus.
     *
     * Generated from protobuf field <code>.flights.SeatClassPolicy seatingPolicy = 29;</code>
     * @return int
     */
    public function getSeatingPolicy()
    {
        return $this->seatingPolicy;
    }

    /**
     * Used to determine the label printed above the seat class on the Google Pay pass. E.g. Economy, Economy Plus.
     *
     * Generated from protobuf field <code>.flights.SeatClassPolicy seatingPolicy = 29;</code>
     * @param int $var
     * @return $this
     */
    public function setSeatingPolicy($var)
    {
        GPBUtil::checkEnum($var, \Flights\SeatClassPolicy::class);
        $this->seatingPolicy = $var;

        return $this;
    }

    /**
     * The status of the flight. This can be manually set, or automatically set for customers subscribing to automatic updates.
     *
     * Generated from protobuf field <code>.flights.FlightStatus status = 30;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * The status of the flight. This can be manually set, or automatically set for customers subscribing to automatic updates.
     *
     * Generated from protobuf field <code>.flights.FlightStatus status = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Flights\FlightStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * If PassKit are generating barcodes, include conditional items. Default false.
     *
     * Generated from protobuf field <code>bool ConditionalItems = 31;</code>
     * @return bool
     */
    public function getConditionalItems()
    {
        return $this->ConditionalItems;
    }

    /**
     * If PassKit are generating barcodes, include conditional items. Default false.
     *
     * Generated from protobuf field <code>bool ConditionalItems = 31;</code>
     * @param bool $var
     * @return $this
     */
    public function setConditionalItems($var)
    {
        GPBUtil::checkBool($var);
        $this->ConditionalItems = $var;

        return $this;
    }

    /**
     * If PassKit are generating barcodes, default airline use data (IATA item 4). This can be overwritten at the flight and boarding pass level.
     *
     * Generated from protobuf field <code>string BarcodeAdditionalData = 32;</code>
     * @return string
     */
    public function getBarcodeAdditionalData()
    {
        return $this->BarcodeAdditionalData;
    }

    /**
     * If PassKit are generating barcodes, default airline use data (IATA item 4). This can be overwritten at the flight and boarding pass level.
     *
     * Generated from protobuf field <code>string BarcodeAdditionalData = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setBarcodeAdditionalData($var)
    {
        GPBUtil::checkString($var, True);
        $this->BarcodeAdditionalData = $var;

        return $this;
    }

    /**
     * Issued, installed, uninstalled and invalidated counts. Metrics are not writable.
     *
     * Generated from protobuf field <code>.io.Metrics metrics = 33;</code>
     * @return \Io\Metrics|null
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    public function hasMetrics()
    {
        return isset($this->metrics);
    }

    public function clearMetrics()
    {
        unset($this->metrics);
    }

    /**
     * Issued, installed, uninstalled and invalidated counts. Metrics are not writable.
     *
     * Generated from protobuf field <code>.io.Metrics metrics = 33;</code>
     * @param \Io\Metrics $var
     * @return $this
     */
    public function setMetrics($var)
    {
        GPBUtil::checkMessage($var, \Io\Metrics::class);
        $this->metrics = $var;

        return $this;
    }

    /**
     * How the flight was created Create mode, manually or automatically.
     *
     * Generated from protobuf field <code>.flights.FlightCreateMode createMethod = 34;</code>
     * @return int
     */
    public function getCreateMethod()
    {
        return $this->createMethod;
    }

    /**
     * How the flight was created Create mode, manually or automatically.
     *
     * Generated from protobuf field <code>.flights.FlightCreateMode createMethod = 34;</code>
     * @param int $var
     * @return $this
     */
    public function setCreateMethod($var)
    {
        GPBUtil::checkEnum($var, \Flights\FlightCreateMode::class);
        $this->createMethod = $var;

        return $this;
    }

    /**
     * For automatically created flights, shows the ID of the designator that bootstrapped the flight record.
     *
     * Generated from protobuf field <code>string designatorId = 35;</code>
     * @return string
     */
    public function getDesignatorId()
    {
        return $this->designatorId;
    }

    /**
     * For automatically created flights, shows the ID of the designator that bootstrapped the flight record.
     *
     * Generated from protobuf field <code>string designatorId = 35;</code>
     * @param string $var
     * @return $this
     */
    public function setDesignatorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->designatorId = $var;

        return $this;
    }

    /**
     * Invalidate passes where either the booking or the flight have been cancelled. Default is ON.
     *
     * Generated from protobuf field <code>.io.Toggle invalidateCancelledPasses = 36 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return int
     */
    public function getInvalidateCancelledPasses()
    {
        return $this->invalidateCancelledPasses;
    }

    /**
     * Invalidate passes where either the booking or the flight have been cancelled. Default is ON.
     *
     * Generated from protobuf field <code>.io.Toggle invalidateCancelledPasses = 36 [(.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param int $var
     * @return $this
     */
    public function setInvalidateCancelledPasses($var)
    {
        GPBUtil::checkEnum($var, \Io\Toggle::class);
        $this->invalidateCancelledPasses = $var;

        return $this;
    }

}

