<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/flights/flight.proto

namespace Flights;

use UnexpectedValueException;

/**
 * For customers subscribing to automatic updates, the flight status will be automatically updated. Status is also writable for manual updates.
 *
 * Protobuf type <code>flights.FlightStatus</code>
 */
class FlightStatus
{
    /**
     * No status is known, or flight is not yet scheduled.
     *
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Flight is scheduled to depart.
     *
     * Generated from protobuf enum <code>SCHEDULED = 1;</code>
     */
    const SCHEDULED = 1;
    /**
     * Flight has left the departure gate, but may not be airborne yet.
     *
     * Generated from protobuf enum <code>DEPARTED = 2;</code>
     */
    const DEPARTED = 2;
    /**
     * Flight is airborne.
     *
     * Generated from protobuf enum <code>INAIR = 3;</code>
     */
    const INAIR = 3;
    /**
     * Flight has landed, but may not yet be at the arrival gate.
     *
     * Generated from protobuf enum <code>LANDED = 4;</code>
     */
    const LANDED = 4;
    /**
     * Flight has arrived at the destination gate.
     *
     * Generated from protobuf enum <code>ARRIVED = 5;</code>
     */
    const ARRIVED = 5;
    /**
     * Flight has been cancelled.
     *
     * Generated from protobuf enum <code>CANCELLED = 6;</code>
     */
    const CANCELLED = 6;
    /**
     * Flight is delayed to depart by at least 15 minutes.
     *
     * Generated from protobuf enum <code>DELAYED = 7;</code>
     */
    const DELAYED = 7;
    /**
     * Flight has been diverted from its scheduled destination and has left the departure gate.
     *
     * Generated from protobuf enum <code>DEPARTED_DIVERTED = 8;</code>
     */
    const DEPARTED_DIVERTED = 8;
    /**
     * Flight has been diverted from its scheduled destination and is airborne.
     *
     * Generated from protobuf enum <code>INAIR_DIVERTED = 9;</code>
     */
    const INAIR_DIVERTED = 9;
    /**
     * Flight has arrived at a location different to its scheduled destination.
     *
     * Generated from protobuf enum <code>ARRIVED_DIVERTED = 10;</code>
     */
    const ARRIVED_DIVERTED = 10;
    /**
     * Flight has left its diverted destination en-route to its original destination.
     *
     * Generated from protobuf enum <code>DEPARTED_RECOVERY = 11;</code>
     */
    const DEPARTED_RECOVERY = 11;
    /**
     * Flight has left its diverted destination airborne en-route to its original destination.
     *
     * Generated from protobuf enum <code>INAIR_RECOVERY = 12;</code>
     */
    const INAIR_RECOVERY = 12;
    /**
     * Flight has landed at is original scheduled destination.
     *
     * Generated from protobuf enum <code>ARRIVED_RECOVERY = 13;</code>
     */
    const ARRIVED_RECOVERY = 13;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::SCHEDULED => 'SCHEDULED',
        self::DEPARTED => 'DEPARTED',
        self::INAIR => 'INAIR',
        self::LANDED => 'LANDED',
        self::ARRIVED => 'ARRIVED',
        self::CANCELLED => 'CANCELLED',
        self::DELAYED => 'DELAYED',
        self::DEPARTED_DIVERTED => 'DEPARTED_DIVERTED',
        self::INAIR_DIVERTED => 'INAIR_DIVERTED',
        self::ARRIVED_DIVERTED => 'ARRIVED_DIVERTED',
        self::DEPARTED_RECOVERY => 'DEPARTED_RECOVERY',
        self::INAIR_RECOVERY => 'INAIR_RECOVERY',
        self::ARRIVED_RECOVERY => 'ARRIVED_RECOVERY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

