<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/member/program.proto

namespace Members;

use UnexpectedValueException;

/**
 * Defines what medium we deliver the recovered pass.
 *
 * Protobuf type <code>members.RecoverPassDelivery</code>
 */
class RecoverPassDelivery
{
    /**
     * redirect to pass url.
     *
     * Generated from protobuf enum <code>DELIVERY_REDIRECT = 0;</code>
     */
    const DELIVERY_REDIRECT = 0;
    /**
     * email user (resend welcome email)
     *
     * Generated from protobuf enum <code>DELIVERY_EMAIL = 1;</code>
     */
    const DELIVERY_EMAIL = 1;
    /**
     * sms to users phone
     *
     * Generated from protobuf enum <code>DELIVERY_SMS = 2;</code>
     */
    const DELIVERY_SMS = 2;

    private static $valueToName = [
        self::DELIVERY_REDIRECT => 'DELIVERY_REDIRECT',
        self::DELIVERY_EMAIL => 'DELIVERY_EMAIL',
        self::DELIVERY_SMS => 'DELIVERY_SMS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

